### ISSUE TITLE
HATEOAS Support

### ISSUE THREAD

**Issue by xogeny** [rs/rest-layer#1]
Olivier, I just came across this project while looking for schema related packages.  There is a lot of overlap between what you are doing here and some stuff I've been tinkering with.  However, one big difference is that I am very much approaching my stuff from a HATEOAS perspective where the API is discoverable and the representations use hypermedia formats like HAL, Siren, etc.

I was just curious if you've thought about such approaches in the context of `rest-layer`?

In any case, I really like a lot of the ideas you've introduced.

P.S. - This isn't exactly an "issue", but your profile doesn't include an email address so I added here.  Sorry for the clutter.  Feel free to contact me by email if you want to take this offline.

**Comment by rs** [comment]
I’ve made the design choice to only use the HTTP body for resource representation and HTTP headers for metadata. You have some basic discoverability when you `POST`, with `Content-Location` header. I may add more headers like that in the future, like for pagination for instance.

I’m not very sold to HATEOAS though. After years of experiences with APIs, I never saw a successful use of API discoverability on the client. It’s a very elegent approach to a problem API consumers don’t have IHMO. At the end of the day, it’s just more data on the wire that nobody use :)

With rest layer it’s very easy to add a custom response sender that implements HATEOAS though.

Thanks for your interest to this project.
