### ISSUE TITLE
Add ErrForbiden to resource package

### ISSUE THREAD

**Issue by smyrman** [rs/rest-layer#120]
It wold be good to add an `ErrForbidden` to the `resource` package so that it may be returned by resource hooks and understood by the `rest` (and `graphql`) package when generating a response.

To avoid having to state a case for _every_ possible HTTP code though, maybe it would be better to let the error be an integer in the `resource` package?
```go
type Error int

func (status Error) Error() string {
        return http.StatusText(status)
}

var (
        ...
        ErrForbidden Error = Error(http.StatusForbidden)
        ...
)
```
Then we don't need a switch-case error-handler in the `rest` package for this specific issue, as we could just convert it like this:
```go
if status, ok := err.(resource.Error); ok {
        return Error{int(status), http.StatusText(int(status)), nil}
} else if err != nil {
        return &Error{520, err.Error(), nil}
} else {
        return nil
}

```

It could also make sense to remove `ErrUnauthorized`, as the handlers for it (in the `rest` package at least) do not set the required `WWW-Authenticate` header. Nor does rest-layer have any built-in knowledge for what the value of this header should be.

We would need to update some examples to reflect this:

I think it should probably be up to the authentication layer (and the authentication layer only) to return a 401 response, and if a request goes past the authentication layer, even if by mistake, and hits a resource hook that e.g. need access to the current user, we return a 403 forbidden.

**Comment by rs** [comment]
Agreed with all the points.

I did not use the HTTP status codes in the `resource.Error` type because I didn't want to "limit" or tie this package to the HTTP transport. I'm find revisiting that.

**Comment by smyrman** [comment]
Yeah I took it that was the reason. We can maybe start out with removing `ErrUnauthorized` (since we can't handle it 100% correct) and add `ErrForbidden` in it's place. Then we can consider _later_ if there is a desire to _optimise_ for HTTP error handling and make that _easier_ than non-http error handling.
