### ISSUE TITLE
Filter query parameter REST example

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [rs/rest-layer#122]
Hi,
In the documentation it is stated that GET and DELETE support `filter` query parameter, however there is no single REST API call example to back it up, so it is not very clear how to format the JSON query in the `filter` parameter. Can you give a simple example for: `{type: {$regex: "re[s]{1}t-la.+r"}}`

Trying:
`GET http://localhost:3001/api/clients?filter={name: {$regex: "Asparu32"}}` gives me:
`"Invalid `filter` parameter: name: invalid query expression: not a string`

`GET http://localhost:3001/api/clients?filter={name: {$regex: "re[s]{1}t-la.+r"}}` gives me:
`"Invalid `filter` parameter: name: invalid query expression: not a string`

`GET http://localhost:3001/api/clients?filter={name: "Asparu32"}`
Works as expected.

Resource defined as:
```
	client = schema.Schema{
		Fields: schema.Fields{
			"id": mongo.ObjectIDField,
			"name": {
				Required:   true,
				Filterable: true,
				Validator:  &schema.String{},
			},
			"address": {
				Required:   true,
				Filterable: true,
				Validator:  &schema.String{},
			},
		},
	}
```
Thanks

**Comment by Dragomir-Ivanov** [comment]
Made a pull request for this.

**Comment by smyrman** [comment]
If found that the DELETE does not seem to respect filter or limit though, it deletes everything... I will open another issue on that.
