### ISSUE TITLE
Add Decimal/Numeric schema type

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [rs/rest-layer#125]
Hi There,
It would be good if Rest-Layer supports Decimal/Numeric schema type, so it can be used in financial applications. DBs supporting decimals naively:
```
MongoDB 3.4+ - NumberDecimal
SQLite3 - NUMERIC
ElasticSearch - scaled_float
```
Any comments appreciated.

**Comment by smyrman** [comment]
It might be best to do this either via the application itself, or via the different storage backend libraries.

E.g. you could add a type `NumericDecimal` that implements the `schema.FieldValidator` and `schema.FieldSerializer` interfaces to `rs/rest-layer-mongo`.

**Comment by smyrman** [comment]
PS!  I would add it to an application first, and if it works well, contribute it back to one of the storage backends (and potentially get it cleaned up a bit).

**Comment by Dragomir-Ivanov** [comment]
Thanks for the comments @smyrman. Will investigate and try to add it in the application. I understand that `Serialize` function is called before data is passed from the `Storer` to the REST response, however I don't understand how things are serialized from other way around. E.g. from REST request to `Storer`. My idea is: 
1. Numeric data is passed as string in JSON request. 
2. Rest-Layer sees that field is `Schema.Numeric` and then validates and converts it to this type.
3. Mongo backend converts `Schema.Numeric` to Decimal128 mongo type.

Thanks for the help, still new to Rest-Layer and Go but is seems great. Is Rest-Layer used somewhere in production?

**Comment by smyrman** [comment]
> E.g. from REST request to Storer. My idea is:

That is the Validator

**Comment by smyrman** [comment]
> I understand that Serialize function is called before data is passed from the Storer 

Correct:-) So here you could return e.g. a `json.RawMessage` to make it simple, or any type that implements the `json.Marshaller` interface.

**Comment by Dragomir-Ivanov** [comment]
Thanks,
Just figured out this myself. This is my first naive implementation:
```
// Decimal type, works with Mongo 3.4+ for now only
type Decimal struct {
	StoreBinary bool
}

// Validate implements FieldValidator
func (v Decimal) Validate(value interface{}) (interface{}, error) {
	s, ok := value.(string)
	if !ok {
		return nil, errors.New("invalid type")
	}
	ip, err := bson.ParseDecimal128(s)
	if err != nil {
		return nil, errors.New("invalid Decimal format")
	}

	return ip, nil
}

// Serialize implements FieldSerializer.
func (v Decimal) Serialize(value interface{}) (interface{}, error) {
	b, ok := value.(bson.Decimal128)
	if !ok {
		return nil, errors.New("invalid type")
	}
	return b.String(), nil
}
```

You are right, this is too specific to include into Rest-Layer itself. It may even drag itself some `decimal` Go library doing `Min/Max` validation. But this is worth including into the Wiki. So one can easily extend Rest-Layer without digging too much.

Now will need to see how going to make this portable to other DBs.
Thanks.

**Comment by smyrman** [comment]
Yes, I think the documentation could be improved. created a new ticket for that, and will close this one. Feel free to keep commenting, or raise a new issue.

>  Is Rest-Layer used somewhere in production?

Given the amount of stars, maybe, but it's not considered stable as such. We do still impose breaking changes every now and then.

**Comment by Dragomir-Ivanov** [comment]
Maybe we still can include the code above in `rs-layer-mongo`, as it is without any `Min/Max` validation, so not drag additional dependencies. Should I send PR?

**Comment by smyrman** [comment]
There are still some open questions actually. Your code above assumes the decimal is encoded as string (e.g. `"value": "4.53"` rather than `"value": 4.53`). Maybe it would be good to support the latter as well? To do that, we actually do need some changes to rest-layer itself, e.g. the decoder could be set to use:

- https://golang.org/pkg/encoding/json/#Decoder.UseNumber

This would affect how exisiting numeric validators a re implemented in test-layer as well. I think maybe I will reopen this so we can consider that...

@rs, any thoughts?

**Comment by smyrman** [comment]
@Dragomir-Ivanov, you can send a PR if you want, but it might be good to figgure out if we _should_ actually change something in rest-layer as well - e.g. switch to using `json.Number` for decoding numbers.

**Comment by Dragomir-Ivanov** [comment]
@smyrman Yes, I totally agree that it would look nice in the JSON request, however keep in mind that decimals most likely will still be kept within `string` type on the front-end. I will look around and revert back.

**Comment by smyrman** [comment]
Yeah, I guess JavaScript would handle it as float if it was not a string, so maybe the non-string encoding has limited use.

**Comment by smyrman** [comment]
Discussion on #128 concluded so closing this issue as there will be no changed done to rest-layer to support this.

Thanks for all your work @Dragomir-Ivanov.
