### ISSUE TITLE
Content-Location not generated correctly with mongo IDs.

### ISSUE THREAD

**Issue by rs** [rs/rest-layer#131]
The `Content-Location` header is not serialized correctly when the ID is a mongo ID.

```
$ bat POST :2015/api/as Authorization:"Bearer ${KEY}" name=n1  
POST /api/as HTTP/1.1
Host: localhost:2015
Accept: application/json
Accept-Encoding: gzip, deflate
Authorization: Bearer XXX
Content-Type: application/json
User-Agent: bat/0.1.0

{"name":"n1"}

HTTP/1.1 201 Created
Last-Modified: Thu, 07 Sep 2017 20:28:37 GMT
Server: Caddy
Content-Length: 45
Content-Location: /as/ObjectIdHex("59b1abf5cee0fb0001ea732e")
Content-Type: application/json
Date: Thu, 07 Sep 2017 20:28:37 GMT
Etag: "5efa3a3f0f355cef35d7ca2464d4836d"

{
  "id": "59b1abf5cee0fb0001ea732e",
  "name": "n1"
}
```

**Comment by Dragomir-Ivanov** [comment]
The problem lies in `encoding/bson` Go package (bug maybe?):
```
// String returns a hex string representation of the id.
// Example: ObjectIdHex("4d88e15b60f486e428412dc9").
func (id ObjectId) String() string {
	return fmt.Sprintf(`ObjectIdHex("%x")`, string(id))
}
```

**Comment by rs** [comment]
We might need to wrap it then.

**Comment by Dragomir-Ivanov** [comment]
@rs Interestingly how `bson.ObjectId` leaks into rest-layer. Shouldn't all such occurrences be wrapped within `github.com/rs/rest-layer-mongo` `ObjectID` type?

**Comment by rs** [comment]
I think so.

**Comment by Dragomir-Ivanov** [comment]
@rs Thanks, will try to fix this issue myself.

**Comment by smyrman** [comment]
Not sure it's in the mongo package.  I used the  rest-layer-mongo.ObjectIDField. Should it not call the serializer method in rest-layer on the location URLgeneration?

https://github.com/rs/rest-layer-mongo/blob/f301bb23e3cb499e6ddd0c9c7210a3d158570f9f/id.go#L57

This method does return a string:
https://godoc.org/gopkg.in/mgo.v2/bson#ObjectId.Hex

**Comment by Dragomir-Ivanov** [comment]
@smyrman Please take a look at the open issue in `rest-layer-mongo`

**Comment by rs** [comment]
@smyrman might be true. Perhaps we should get the validator of the `id` field and use the validator's serializer if provided. This way we wouldn't have to wrap the ObjectID.

**Comment by Dragomir-Ivanov** [comment]
@rs Might be cleaner solution.
