### ISSUE TITLE
Adding a bool parameter to a field does not parse correctly

### ISSUE THREAD

**Issue by smyrman** [rs/rest-layer#140]
It seams the current query parser does not handle bool values in field parameters.

Example:
 
If I use a boolean validator like this:
```go
schema.Schema{
	Fields: schema.Fields{
		"items": {
			 Params := schema.Params{
				"expand": {Validator: &schema.Bool{}},
			},
		},
	},
}
```

If I now ask for `fields=items(expand:true)`, I will get an error when trying to filter on a `rest` resource:
```
HTTP/1.1 422 Unprocessable Entity
Content-Length : 81
Content-Type : application/json
Date : Fri, 22 Sep 2017 07:04:44 GMT
Server : Caddy
Vary : Origin


{
  "code": 422,
  "message": "Invalid `fields` parameter: looking for value at char 13"
}
```

**Comment by smyrman** [comment]
As a FYI, I have worked around this using an integer that may be 0 or 1, but we should probably address this? I think this also relates to #139, or at least, they are both issues with the current query parser implementation.

**Comment by smyrman** [comment]
Needs case for `t` and `f` here:

https://github.com/rs/rest-layer/blob/b0185e617e9718fea09957f10126b020d04bc033/schema/query/projection_parser.go#L215

**Comment by rs** [comment]
Good catch, will you fix it or should I?

**Comment by smyrman** [comment]
If you want to fix it, that would be great. If not, I _might_ have some time next week.

There is a need for a  new method `projectionParser.parseBool()`, although I see you got an implementation of this for another parser type here:

https://github.com/rs/rest-layer/blob/b0185e617e9718fea09957f10126b020d04bc033/schema/query/predicate_parser.go#L378
