### ISSUE TITLE
Returning whole resource, along with its sub-resouce

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [rs/rest-layer#147]
Right now, having a query:
`api/shema/[id]` works and returns all fields without the referrers
`api/shema/[id]?fields=id,name,sub` works and returns `id` and `name` of the `shema` resource and its `sub` sub-resource.

The problem is that we can't have both. Would like to return all the fields of the schema without specifing them one by one. Something like:
`api/shema/[id]?fields=*,sub`

**Comment by smyrman** [comment]
>  If I remove the appliances sub-resource, it filters them

This sounds like a bug. Do you mind raise this as a separate issue?

**Comment by Dragomir-Ivanov** [comment]
@smyrman  In a second. Can you look at issue #123 and test this at your side. It might be real after all.

**Comment by smyrman** [comment]
#148 raised to deal with the buggy part.

This issue will deal with how _expand_ one or more fields while still returning all fields without having to _list_ all fields.

**Comment by Dragomir-Ivanov** [comment]
PR #155

**Comment by Dragomir-Ivanov** [comment]
Guys I want to revive discussion on this topic. I did a PR #155 about it, however we didn't agreed on solution, so it got stale. I don't want anything fancy, just want to have a way to get all fields of resource/sub-resource. My motivation is as follows:
1. Development speed. It is more convenient to say `?fields=*,reference{*}` than manually adding each new field you add to resources during development sprints.
2. Since `?fields=reference{}` doesn't work, and `rest-layer` returns error `ParseProjection unexpected error: looking for field name at char 10`, client of the REST API doesn't have a way to know the shape of `reference` resource. This can be a real bumper, especially of lacking docs and if `reference` resource is not accessible from `index` but only used as sub-resource. 

I have a private patch that seems to work, and it allows queries like these:
```
?fields=*,reference{*}
?fields=*,n:name        // This will return name and n, as alias to name
?fields=reference{*}(filter:{name:"foo"}}
?fields=reference{*,user{*}}
```
I want to make this right, so no rush. In the meantime I will use mine patch.
Your input appreciated.

**Comment by smyrman** [comment]
Just to clarify, I assume `reference` in your example is meant to be a field-name. With that assumption, I think your way of handling it makes sense to me.

I want to raise though, that I think the most useful use-case or a `*` expansion, would be to allow expanding references in a map where all the fields can't necessarily be known in advance. E.g. consider a field:

```go
"refmap": `{
    Validator: &schema.Dict{
        Value:schema.Field{
            Validator: schema.Reference{Path: "foo"},
        },
}

```

**Comment by Dragomir-Ivanov** [comment]
Thanks for the response Sindre. However I have no experience with `schema.Dict` and `schema.Object` and don't quite understand what the snipped above accomplishes. Perhaps you can make some small real live examples that I can try understand, and try to use them as test cases.

**Comment by smyrman** [comment]
Given an existing resource `foo` with at least an ID fied, consider another resource `bar` with schema:

```go
barSchmea := &schema.Schema{
    Fields: schema.Fields{
        "id": schema.IDField,
        "refmap": `{
            Validator: &schema.Dict{
                Value:schema.Field{
                    Validator: schema.Reference{Path: "foo"},
                },
        },
}

```

Now we should be allowed to upload documents with arbitrary keys in the `"refmap"` field, and references to the "foo" resource as values. E.g.
```json
{"refmap":{"x": "1", "y": "2"} }
 ```

Now, there would be nice if there was a way to embed the linked foo resources without knowing the field names in all documents. E.g. `GET /bar?filelds=refmap{*}` giving: 

```json
{"refmap":{"x": {"id":"1", "name": "foo1"}, "y":  {"id":"2", "name": "foo2"}}}
```

**Comment by smyrman** [comment]
Probably doesn't work.

**Comment by Dragomir-Ivanov** [comment]
Okay, got `posts?fields=refmap{*{*}}` working. It makes sense, the first star displays all the fields within the dict, the second star, expands those fields, if they are `Reference, Connection, or Dict/Object`

**Comment by smyrman** [comment]
Awesome. Thanks for that.
