### ISSUE TITLE
$regex value operators in filter not working

### ISSUE THREAD

**Issue by smyrman** [rs/rest-layer#149]
See details in #123 discussion ~$nin, $ne, $in,~ $regex appears broken.

PS! @rs, is `$regex` expected to work for all storage engines now?

**Comment by Dragomir-Ivanov** [comment]
@smyrman 
There is no operator `$neq`. All available ones are:
```
const (
	opAnd            = "$and"
	opOr             = "$or"
	opExists         = "$exists"
	opIn             = "$in"
	opNotIn          = "$nin"
	opNotEqual       = "$ne"
	opLowerThan      = "$lt"
	opLowerOrEqual   = "$lte"
	opGreaterThan    = "$gt"
	opGreaterOrEqual = "$gte"
	opRegex          = "$regex"
)
``` 
defined in `schema/query/predicate.go`

With this patch applied:
https://github.com/rs/rest-layer/pull/123/commits/3f0f2f7b82711f2c082e45d75686cafd90d3059d
`$ne`,`$in`,`$nin` all work.

**Comment by rs** [comment]
@smyrman: only the one who can support it.

**Comment by smyrman** [comment]
@Dragomir-Ivanov reports on (#123)

> Just did fresh go get on my project. $ne,$nin,$in work out of the box. It is just $regex need the patch above.

Don't know why it did not work for me in my test...

**Comment by Dragomir-Ivanov** [comment]
Does it work now? Is there any way we can chat outside github, not to pollute here?

**Comment by smyrman** [comment]
> Does it work now?

For me, no. I still get the same errors with the example given in #123. @Dragomir-Ivanov are you using the test code from the issue when this works for you, or some other code?

Steps to reproduce, given you change the ID field in the users resource to be a String as described in the patch on #123.

```sh
$ http PUT :8080/api/users/john name="John Doe"
$ http PUT :8080/api/users/john name="John Doe"
$ http PUT :8080/api/users/mike name="Mike Doe"
``

And finally, to get the 400 errors:
```sh
$ curl -g 'http://localhost:8080/api/users?filter={name:{$in:["John Doe"]}}'
400 Bad Request
$ curl -g 'http://localhost:8080/api/users?filter={name:{$nin:["John Doe"]}}'
400 Bad Request
$ curl -g 'http://localhost:8080/api/users?filter={name:{$ne:"John Doe"}}'
400 Bad Request
```

I use `dep` to ensure that the `vendor` folder is populated:
```sh
$ dep init
$ dep ensure -update
```
Below is my `Gopkg.lock` file:
```toml
# This file is autogenerated, do not edit; changes may be undone by the next 'dep ensure'.


[[projects]]
  branch = "master"
  name = "github.com/justinas/alice"
  packages = ["."]
  revision = "1051eaf52fcafdd87ead59d28b065f1fcb8274ec"

[[projects]]
  name = "github.com/rs/cors"
  packages = ["."]
  revision = "7af7a1e09ba336d2ea14b1ce73bf693c6837dbf6"
  version = "v1.2"

[[projects]]
  branch = "master"
  name = "github.com/rs/rest-layer"
  packages = ["resource","rest","schema","schema/query"]
  revision = "0df312935ab2631d1813920adf9bb04b328dd071"

[[projects]]
  branch = "master"
  name = "github.com/rs/rest-layer-mem"
  packages = ["."]
  revision = "25a468b0b8d157b9cb8db4126e85b3311f80a537"

[[projects]]
  branch = "master"
  name = "github.com/rs/rest-layer-mongo"
  packages = ["."]
  revision = "f301bb23e3cb499e6ddd0c9c7210a3d158570f9f"

[[projects]]
  name = "github.com/rs/xid"
  packages = ["."]
  revision = "02dd45c33376f85d1064355dc790dcc4850596b1"
  version = "v1.1"

[[projects]]
  name = "github.com/rs/zerolog"
  packages = [".","hlog","internal/json","log"]
  revision = "3ac71fc58dbd43122668a912b755b0979ba9ce1f"
  version = "v1.3.0"

[[projects]]
  name = "github.com/zenazn/goji"
  packages = ["web/mutil"]
  revision = "64eb34159fe53473206c2b3e70fe396a639452f2"
  version = "v1.0"

[[projects]]
  branch = "master"
  name = "golang.org/x/crypto"
  packages = ["bcrypt","blowfish"]
  revision = "9419663f5a44be8b34ca85f08abc5fe1be11f8a3"

[[projects]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"
  packages = [".","bson","internal/json","internal/sasl","internal/scram"]
  revision = "3f83fa5005286a7fe593b055f0d7771a7dce4655"

[solve-meta]
  analyzer-name = "dep"
  analyzer-version = 1
  inputs-digest = "2bd06e8fcf26ced2754945b0678cbda5d5eb503c2902a1599ed5c1ad3d9b84ff"
  solver-name = "gps-cdcl"
  solver-version = 1

**Comment by smyrman** [comment]
> Is there any way we can chat outside github, not to pollute here?

I would prefer for this particular thread of discussion to be on the issue. Other than that we don't currently have a chat set up for this project.

**Comment by smyrman** [comment]
I think it's just my filter syntax in curl that's wrong 🤕

**Comment by smyrman** [comment]
This works 😊 

```sh
$ http GET ':8080/api/users' 'filter=={name:{$ne:"John Doe"}}'
$ http GET ':8080/api/users' 'filter=={name:{$nin:["John Doe"]}}'
$ http GET ':8080/api/users' 'filter=={name:{$in:["John Doe"]}}' 
```

**Comment by Dragomir-Ivanov** [comment]
Good :)

I was asking for a chat, because wanted to ask several potential stupid questions. Might open another ticket for those.

**Comment by rs** [comment]
If you think those questions might benefit others, it is better to open tickets. We can also create a rest-layer channel on gopher’s Slack.

**Comment by rs** [comment]
I just created the #rest-layer channel if you guys want to join.

**Comment by Dragomir-Ivanov** [comment]
@smyrman Can we close this card. Can you check the patch on #123

**Comment by smyrman** [comment]
@Dragomir-Ivanov, I think @rs is still a bit sceptical about allowing any Stringer value to be converted to a string by the `schema.String` validator. Is there another way to fix it?

**Comment by smyrman** [comment]
fixed

**Comment by smyrman** [comment]
@rs /  @Dragomir-Ivanov just to clarify, the way understand the code I "fixed", the query package sends the parameter to operators such as "`$lt` `$ne`, `$regex` to the FieldValidator for the field it's used on, is that correctly understood?

E.g.

If I ask for `?filter={name: $regex: "^test.*$"}`, " "^test.*$" will be sent to the `FieldValidator` for `"name"`, and if I ask for  `?filter={number: $lt: 1000}`, `1000` is sent to the `FieldValidator` for `"number"`.

If this is what is happening, it strikes me as wrong. What if I had a `"number"` validator of `schema.Float{Limts:schema.Limits{Max:999}}` or  a `"name"` validator `schema.String{Allowed:[]string{"testA","testB","testC"}`.Then the validation of the query would fail although its actually perfectly valid. The only thing we are actullly interested in knowing is:

1. Is the operator legal for this field.
2. Is the value for this field legal according to the given FieldValidator

Could it be an idea to add an aditonal variable that's implemented by specific `FieldValidators` ala:

```go
type OpValidator interface{
    ValidateOperator(op string, value interface{}) (value, error)
}
```

We should be aware of how this may affect e.g. support for $lt / $gt queries against e.g. DateTime fields.

I will raise a new issue for this, just polling you to check that I have understood this correct dfirst.

**Comment by rs** [comment]
Yes you are correct. The idea was to use the validator to check and normalize for the correct type but I did not think about other validator criteria.

**Comment by smyrman** [comment]
Cool, I will create a separate issue for it.
