### ISSUE TITLE
Sub-resources `Total`

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [rs/rest-layer#150]
It is fantastic that we can filter on the sub-resources, e.g:
```
GET http://192.168.0.103:3001/api/clients/59a1a17aeaba9ebd0180abb0?fields=id,name,services(page:1,limit:10)
```
However we don't receive the total count for this `services` sub-resouce. Trying:
```
GET http://192.168.0.103:3001/api/clients/59a1a17aeaba9ebd0180abb0?fields=id,name,services(page:1,limit:10,total:1)
```
Gives `Invalid "fields" parameter: services: unsupported param name: total`

This feature has good use-case. Where you populate initial view with several sub-resources, show their pagination options, then allow further paginate them individually, through `index` bound resource, and not sub-resource.
More-over having `X-Total`,`X-Count` HTTP response headers is a bit unconventional.

My proposal is to wrap our responses in a holder object, something like that:
```
{
    total: X,
    data: {...}
}
```

**Comment by Dragomir-Ivanov** [comment]
The other way is I guess, to have dedicated `count` REST method, and obtain `Total` in subsequent REST requests.
```
GET http://192.168.0.103:3001/api/clients/count?filter={}
```

**Comment by smyrman** [comment]
Just some generic feedback first

I don't think neither me nor @rs is a huge fan of wrapping the data response in a sub-structure (by default). There is an option to create your own response formatter if you would want that kind of response.

> More-over having X-Total,X-Count HTTP response headers is a bit unconventional.

Not really, although there are certainly other approaches. Using Header s is a nice way of not forcing the consumer of API to deal with extra values, such as the `X-Total` header, which you would do by wrapping the response.

This does not bring us closer to solve your pagination problem, but quite frankly, if you want to paginate a resource, would you not want to list that resource directly via a separate response rather than embed it?

**Comment by Dragomir-Ivanov** [comment]
I totally agree that wrapping it is ugly. The reason is the same, as sub-resources are advertised: "To lower REST requests count". 

How about `count` method on a resource, I don't think `rest-layer` has it now. Seems like a good feature.

**Comment by smyrman** [comment]
I am not sure I understand exactly what would the `count` method do?

If we have a `parent-resource` and `sub-resource`, could you give some exmples of how you think it should work, and what it should return?

**Comment by Dragomir-Ivanov** [comment]
The idea is `count` to return how many items match a criteria, without actually returning the items. The result of `Counter` interface actually. However I found a way to emulate this, but it will return at least one item.
```
GET http://192.168.0.103:3001/api/clients?limit=1&total=1&filter={"name":{"$regex":"^A"}}
```

Interestingly enough, using `limit=0` returns all items. Bug maybe?

**Comment by Dragomir-Ivanov** [comment]
Okay, yes, Issue in MongoDB or rest-layer-mongo, will investigate.

**Comment by smyrman** [comment]
> Okay, yes, Issue in MongoDB. If you are willing to support `limit=0`

I'm not against it if you can find a way to implement it. I am also not against there being some way of retrieving the total count of a sub-resource, if it does not involve wrapping the data response by default.

 @rs, what do you think about `limit=0`?

**Comment by rs** [comment]
Why don’t you use HEAD instead?

**Comment by smyrman** [comment]
Good point

**Comment by Dragomir-Ivanov** [comment]
@rs @smyrman Thanks, totally forgot about HEAD. It works as expected, however it is little ineffective for `resource.ItemList` right now, i.e. actually retrieving the data from the DB, just not sending it back. I guess we can use `Counter` interface if `total=1` is used, and not retrieve all data.
HEAD for `resource.Item` will stay as it is in order to obtain the ETag.

**Comment by smyrman** [comment]
@Dragomir-Ivanov, looks like the code is at least trying to set the limit to 0 on `HEAD` requests:

https://github.com/rs/rest-layer/blob/b96a9fac46d267ad2894ec98b0bf242a703a45a9/rest/routing.go#L198

And in rest-layer-mongo:

https://github.com/rs/rest-layer-mongo/blob/4b10584d0513745d36ba07e93d3acc8f92323231/mongo.go#L213

Did you find that this was not the case?

**Comment by smyrman** [comment]
Other than that, I would assume it still makes sense to prefer the Counter interface, if implemented, for the `HEAD` request.

**Comment by Dragomir-Ivanov** [comment]
@smyrman Yes, this is a MongoDB issue.
[https://docs.mongodb.com/manual/reference/method/cursor.limit/#zero-value](url)

There are 2 ways of approaching this.
1) Fix this in `rest-layer` and use `Counter` interface. We can revert back to `Find` with stripped body if `Counter` is not available.
2) Fix this in `rest-layer-mongo`s `Find` and add a specialization like this:
```
// Find items from the mongo collection matching the provided query
func (m Handler) Find(ctx context.Context, q *query.Query) (*resource.ItemList, error) {
	if q.Window.Limit == 0 {
		n, err := m.Count(ctx, q)
		if err != nil {
			return nil, err
		}
		list := &resource.ItemList{
			Total: n,
			Limit: q.Window.Limit,
			Items: []*resource.Item{},
		}
		return list, err
	}
....
```

I can send PR, for whatever way you choose.

**Comment by smyrman** [comment]
I would actually prefer both, if you have time @Dragomir-Ivanov, but maybe prioritize 2.

I see 2 as a bug that should be fixed so that at least the `rest-layer-mongo` acts as expected when the limit is set to 0 (for any reason).

I see 1 as a generic _optimization_ that _may_ help certain storage backends to perform the count operation for HEAD requests more efficiently.

@rs, I hope this is fine with you.

**Comment by smyrman** [comment]
PS! For 2, please add a comment with a link to the bug so that it's clear why this work-around is there, and so that it may be eventually removed if the issue is fixed.

**Comment by Dragomir-Ivanov** [comment]
Okay, lets wait for @rs comment.

**Comment by rs** [comment]
agreed

**Comment by Dragomir-Ivanov** [comment]
Should use HEAD request for resource total.
Mongo issue fixed in https://github.com/rs/rest-layer-mongo/commit/e32a6d3bbf5704ba53a9319054cd7092aa1ab871
