### ISSUE TITLE
Setting `Cache-Control` HTTP response header for item

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [rs/rest-layer#156]
When a request for item is missing the `ETag` HTTP request header, this means that the browser sees the item for the first time. `Chrome` (maybe other browsers too) will attempt to cache the item as it is and will continue serving it from the disk cache. In order to prevent that, we need to set `Cache-Control: no-cache` HTTP response header, or at-least provide a hook letting user decides what to return to the browser.

We can't do this in onFind/onFound hooks, because we don't have request headers ( but we have `route` within the `Context`).

What is the best way to implement this?

**Comment by rs** [comment]
We could add a cache section to the endpoint binding configuration. Those configuration directive could then be used by the rest package to generate the proper `Cache-Control` header.

**Comment by smyrman** [comment]
Would it be a viable option _not_ to make it configurable, and, at least initially, always return `Cache-Control: no-cace`when appropriate? Or are there valid use-cases for _not_ setting the `Cache-Control` header to this value?

**Comment by Dragomir-Ivanov** [comment]
@rs this could work, but we will need to deferential the setting for `item` and `list` cases.
@smyrman I guess there will be cases when user will want to set the cache expiration to some value other than 0.

And again, isn't this a job for post `rest-layer` middleware function?

**Comment by rs** [comment]
You may want to accept stale values on the client for some time in certain contexts. Ok to start with static `no-cache` so clients will still store responses for revalidation.

**Comment by Dragomir-Ivanov** [comment]
Static `no-cache` can be implemented easily by custom `ResponseFormatter`.
