### ISSUE TITLE
Investigate using less pointers for resource.ItemList and resource hooks

### ISSUE THREAD

**Issue by smyrman** [rs/rest-layer#158]
This issue will investigate if we can:
1. modify `resource.ItemList` to contain a list `Items []Item` rather than `Items []*Item`.
2. ~avoid double-pointer usage of `**resource.ItemList` and `**resource.Item` in resource EventHook interfaces.~

The goal of this issue is two-fold. This will reduce the complexity of the library for then end-user, by disallowing nil-values for Item in lists. The other goal is to get some performance wins in terms of achieving fewer and bigger allocations to the heap. This should be backed up by benchmarks.

Links to code:
https://github.com/rs/rest-layer/blob/884a12929af166dd059e30fb50555bd8622861af/resource/item.go#L10
https://github.com/rs/rest-layer/blob/884a12929af166dd059e30fb50555bd8622861af/resource/item.go#L27
https://github.com/rs/rest-layer/blob/884a12929af166dd059e30fb50555bd8622861af/resource/hook.go#L28
https://github.com/rs/rest-layer/blob/884a12929af166dd059e30fb50555bd8622861af/resource/hook.go#L58

EDIT: descriptive text updated after striking out point 2.

**Comment by rs** [comment]
For the double-pointers, how would you handle cases where the item is `nil` and the handler wants to make it non-`nil` or the opposite?

**Comment by smyrman** [comment]
What is the use-case of making an item nil?

**Comment by smyrman** [comment]
If an item _can_ be nil, users would also have to check for it in their `hook` implementation, which is error prone and easy to forget.

It's still possible to set `Item.payload` to nill. It's also possible to adda field `Ignore bool` to Item, _if_ there is a strong use-case for it.

**Comment by smyrman** [comment]
Yeah, I realise why double pointers are used now! Let's strike point 2, and just look at replacing `[]*Item` with `[]Item`. That also gives a very limited and clear scope for the issue.

**Comment by smyrman** [comment]
closing this issue.
