### ISSUE TITLE
Bypass Store from FindEventHandler

### ISSUE THREAD

**Issue by lordnynex** [rs/rest-layer#16]
Hello,

It looks like FindEventHandler does not support any return except error. Is there any way to implement caching to bypass going to the store? 

It seems like the only way to do this at present is to implement your own storage extension. 

Is there any plans to support 'tiered' storage extensions? I think the ES storage extension is very good, but in most cases ES is not used as a canonical store. A tiered storage extension would allow for a canonical store that can utilize ES (or redis) as a secondary index which can be guaranteed 'up to date' with the final storage backend through use of hooks.

**Comment by rs** [comment]
If I understand your question correctly, you would like to return a `ItemList` response from the `FindEventHandler` without going through the data storage, am I right? Do you have a practical exemple of the use of such behavior?

What you could do is to return a custom error in the `FindEventHandler` and implement a `FoundEventHandler` that set this specific error to `nil` and provide your own `ItemList. The error in the "pre" hook `Find…` will skip the storage request, but the "post" hook `Found…` is always called to let you modify the final response. But the best option would be certainly to wrap your storage handler.

That second option lead me to your second question about tired storage handlers. The best way to implement that would be to create a storage handler wrapper. I plan on providing a generic wrapper that can route requests to two distinct storage handlers. The routing could be based on methods, like reads on ES and writes on Mongo or some more complexe logic that you could customize via custom code.
