### ISSUE TITLE
Improve query operator validator

### ISSUE THREAD

**Issue by smyrman** [rs/rest-layer#170]
As discussed in #149 (after the fix), query operators (`$ne`, `$regex`, `$lt` etc.)  currently get their values validated with the associated `FieldValidator` as normal values which is inaccurate.

 E.g. ` ?filter={name:{$regex:"^test.*$"}}`, `"^test.*$"` would be validated by the `FieldValidator` for `name`, which is inaccurate in the case where `name` has additional validation criteria, such as `Allowed: []string{"testA", "testV"}` or `Regex`.

What we instead want to validate is,
- Does the operator make sense for the assicated `FieldValidator`?
- Does the operator value have the correct type according to the selected `FieldValidator`?

One way to do this, could be a new optional interface for `FieldValidator` as mentioned in #149.

**Comment by smyrman** [comment]
Interface suggestion:

```go
// OpValidator is a an optional interface for FieldValidator implementations use to allow 
// operator queries when using the rest-layer schema/query package.
type OpValidator interface{
    // ValidateOperator should validates a value operator such as $ne, $lt, $gt, $regex etc, and return
    // either a value that can be used for querying the storage backend, or an error if the operator is
    // not allowed, or the operator value is invalid.
    ValidateOperator(op string, value interface{}) (interface{}, error)
}
```

**Comment by Dragomir-Ivanov** [comment]
@smyrman Can you give one more complete example why we need this. These operators are query only, so they don't update any values, thus is `Allowed` even applicable to them?
Maybe there is a good case for your proposal, I just don't completely understand.

**Comment by smyrman** [comment]
> thus is Allowed even applicable to them?

That is exactly the point, it is not, so when validating an operator values, additional options set in the `FieldValidator` should be ignored.

E.g. `name:{$regex:"^test.*$"} would fail to validate (although it's a valid query), if the `FieldValidator` of `name` (most likely a `schema.String`), provides additional validation options such as `Allowed`, `MinLen`, MaxLen` or `Regex`.  Therefore we *can not* simply call `Validate` on the field's `FieldValidator` instance.

The same is true for numbers. `number:{$lt:1000}` is valid even if the `FieldValidator` for `number` has an upper limit for the value set to `900`.

In adition to that, I suspec that adding the new optional interface could allow even better queries, as we might be able to use the interface e.g. to allow `$lt` and `$gt` queries on non-numeric fields such as e.g. `schema.Time`.

**Comment by Dragomir-Ivanov** [comment]
Ah, I understand now. Basically if you have a `schema.String` field, with `Allowed: []string{"testA", "testV"}` then this regex `^test.*$` will be tested against "testA" and "testV". It is strange we are validating at all in a query, though.

**Comment by smyrman** [comment]
> It is strange we are validating at all in a query, though.

Not really, as we want to validate that it's the right type, and as I said, we probably want to validate that the query parameter make sense for the given field-type. E.g. a `$regex` or `$lt` query makes little sense against a `schema.Dicte` type.

**Comment by Dragomir-Ivanov** [comment]
Yes, you are right. If we go this road it will not manifest in the user code, right. E.i. on the schema definition.

**Comment by Dragomir-Ivanov** [comment]
Shouldn't we close this?

**Comment by smyrman** [comment]
Closing it. Thx for your work @Dragomir-Ivanov.

**Comment by smyrman** [comment]
wrong button.
