### ISSUE TITLE
Document behavior of resource hooks when called from the rest package

### ISSUE THREAD

**Issue by smyrman** [rs/rest-layer#171]
When sending a PATCH request to the `rest` package, OnFound resource hooks get's triggered. This can cause issues when:

- The OnFound hook adds fields or does changes too the response that should not be written.
- The OnFound hook is expensive.

https://github.com/rs/rest-layer/blob/326f8072a1edb7738b3e4bed8a573a0c2ffdfe29/rest/method_item_patch.go#L27

There might be valid use-cases for running the OnFound hook on PATCH, e.g. when the hooks manages an on-read data migration, however this is still best done explicitly through an OnUpdate hook that migrates `original`.

## Solution

There is a simple enough solution. Since we are using context.Context we can use it to signal the resource package to skip hooks. E.g.

```go
// In package resource somewhere.
DisableHooks(ctx context.Context) context.Context {
    // ...
}

// In the linked rest code:
 if l, err := rsrc.Find(resource.DisableHooks(ctx), q); err != nil { 
```
Update all places where hooks gets called to check for the `ctx.Value` set by `DisableHooks` .

**Comment by rs** [comment]
I a hook changes the response on `Find`, shouldn't this alteration be consistent over all calls to `Find`? Do you have a concrete example of a case when `OnFound` hooks would be problematic?

I think the solution is documentation: we should explain that if you alter the result in `OnFound` you must make sure to revert this alteration on write hooks to prevent incremental corruption of the data.

**Comment by smyrman** [comment]
In our concrete case we habe some virual URL fields (called dataURL) that are generated on OnFound, OnUpdated, onCreated. These require DB lookups in some cases. These fields are listed in the schema for documentation purposes.

 When we do a PATCH request for an unrelated field, rest-layer implement this by calling Find to find the original, whitch triggers this hook. When the hook is called, we get a failure during prepare Prepare before resource.Update is even called, so removing the fields in the update hook is not an option.

**Comment by smyrman** [comment]
I.e. we don't want the implementarion specific details of how PATCH ( and currently also GET) is implemented, to be considered by the end-user, who would ecpect only OnUpdated to be called in a rest PATCH request. Don't you agree?

**Comment by rs** [comment]
Perhaps the right solution would be to make it easier to add a virtual fields by making them part of the schema. Imagine with a GraphQL client or GRPC, such unexpected field would break the serialization.

Those hooks are at a lower layer, and other layers should not be able to disable them; especially not thru context, which is a terrible API. If we start add ing such hidden exceptions, it will become very hard to understand when those hooks are triggered or not. I’m sure some other cases would expect those hooks to be triggered in the PATCH case.

**Comment by smyrman** [comment]
Let's continue the discussion here for now, and let the PR rest until we have a final proposal that we agree on.

> Perhaps the right solution would be to make it easier to add a virtual fields by making them part of the schema.

Maybe, I will try to explain a reproduce-case of our use-case below, and we can discuss the specifics.

> Those hooks are at a lower layer, and other layers should not be able to disable them

I suppose you are right. I have nothing against low-level hooks as such, I guess I just expected them too match the actual higher level HTTP calls  i make to the `rest` package, which sadly they do not. Maybe they should? E.g. by letting the `resource.Resource.Update` handle the fetching of `origin`, and only take in the proposed "patch"? It would certainly make reasoning about when they are called possible without knowing `rest` package internals.

## Reproduce case
I will use pseudo-code to save some time, but hopefully it's understandable what is meant. Compared to our concrete case, this case is greatly simplified when it comes to the criteria that influence the field generation, but it should provoke similar issues.

We have three `rest` resources, let's call them `foo` and `bar` and `baz`:

```yaml
foo:
  Fields:
    id: schema.IDField

bar:
  Fields:
    id: schema.Field
    foo:
      Required: true
      Validator: schema.Refernce{Path:"foo"}
    dataURL: # This field never exists in the DB
      ReadOnly: true
      Validator: schema.URL

baz:
  Fields:
   id: schema.Field
    bar:
      Required: true
      Validator: schema.Refernce{Path:"bar"}
    dataURL: # This field never exists in the DB, but we want it to appear in Swagger.
      ReadOnly: true
      Validator: schema.URL
```
We have a hook OnFound to generate the content of `dataURL`:

- Data generation of `dataURL` in `bar`, depends on the values of field `foo` in the `bar` item instanse, so  we must do it as a `hook` rather than as a FieldHandler.

-Data generation of `dataURL` in `baz`, also depends on the values of field `foo` in the `bar` item instance, so  here we even need an extra DB lookup to populate the field.

The error we would get without the patch I proposed in #172, is something like:
```yml
status: 422
error: The Document contain error(s)
issues:
  dataURL: not a valid URL
```

This error looks to be raised after line 27, but before line 63
https://github.com/rs/rest-layer/blob/326f8072a1edb7738b3e4bed8a573a0c2ffdfe29/rest/method_item_patch.go#L27
https://github.com/rs/rest-layer/blob/326f8072a1edb7738b3e4bed8a573a0c2ffdfe29/rest/method_item_patch.go#L63

If I where to guess, it's raised here:
https://github.com/rs/rest-layer/blob/326f8072a1edb7738b3e4bed8a573a0c2ffdfe29/rest/method_item_patch.go#L46

**Comment by smyrman** [comment]
As an FYI, we generate more than one field, and the data set by `OnFound`, is defenanty valid according to the schema. However, we are neither interested in validating nor even generating the data....

We are actually neither interested in generating nor validating this data on the "original" object when we do PATCH of an unrelated field. I suppose of the `rest` package could set the URL _method_ in the context (PATCH, GET, POST), and maybe if we are in the detail view or in the list view, we could _rely_ on that specific information in _our own_ hook to conditionally skip field generation.

**Comment by smyrman** [comment]
> I suppose if the rest package could set the HTTP method in the context (PATCH, GET, POST ,PUT, HEAD), and maybe if we are accesing the single item view or list view

Aftwr inspecting the code som more, looks like I can already posible from the rest-package with `RouteFromContext`. If that works I am happy we close this issue.

I also see there is an exposed `IndexFromContext`. I suppose that one we should eventually drop?

**Comment by smyrman** [comment]
`RouteFromContext` works like a charm. Re-labeled to documentation.
