### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by teloon** [rs/rest-layer#18]
Hi, I was investigating restful framework written with go for our new product and found this great one. Thanks for your effort!

It seems to me this framework is in good enough shape to use for real product in production.(?)  But I still have several concerns:

1. What's the roadmap for sql, specifically mysql, support? I can create my own handlers for now, but it seems I also need to translate the `lookup` struct to mysql.

2. This framework seems to be created originally for nosql db, e.g. the concept of document, field selection etc and using etags to do concurrency control in db(mysql transaction naturally does the trick). Do I need to worry about any performance issue if using sql database?

**Comment by rs** [comment]
I don't think SQL support would be hard to implement, you will just have to make sure that your REST Layer schema matches your SQL schema. The main task as you said is to translate {{lookup}} into SQL statements. Nothing impossible here.

For concurrency control, mysql transaction wouldn't do the trick alone. Etag based concurrency control allows consistency and concurrency guaranty from the client to the storage layer when activated along the line. You can implement the storage's part of the etag system using a transaction to make sure the etag CAS operation is performed atomically.

In term of performance, it really depends on which fields you allow to be filterable. If all those fields have the right indices, you should get good performance overall. But REST Layer is no magic ; Performance will depend on your data, you schema and your indices.

**Comment by teloon** [comment]
Got it, that sounds good to me!

Another question is: the storage layer of this framework is abstracted to FIND/DELETE/INSERT/UPDATE/CLEAR with some slicings and filterings by table field. But in some cases, more complex queries than plain datagraph exploring may be needed, e.g. a place search endpoint which accepts latitude and longitude, we need to add a distance formula to sql query; or in some more complex case we need to do some arbitrary query.

Any idea what's the best way to do this?

**Comment by rs** [comment]
Is see two ways:

1. Add some new operators to the {{lookup}} struct that would be optional to implement. Storage handlers have to return a `resource.ErrNotImplemented` error when the query can't be fully handled. I already have in my TODO to add full text search operator that way.
2. For more complexe / custom queries, you may implement your own custom storage handler that could wrap an existing one and trigger special queries when certain conditions are met. Such condition could be triggered by a custom route or a virtual field with some named filters that trigger specific db queries.

I plan on providing a special storage handler meant to route requests on different wrapped storage handlers based on conditions. You could use that kind of storage handler wrapper to mix an elastic search handler to take care full-text searches with a fallback on another storage handler for other kinds of queries for instance.
