### ISSUE TITLE
rest-layer-mem

### ISSUE THREAD

**Issue by laahs** [rs/rest-layer#19]
Good evening,

just a rapid verification: I just came back from vacation and wanted to go back to the api I am writing, trying to play with rest-layer to evaluate it.

Using rest-layer-men (I have not plugged a real database yet), I can post 10 times to the same resource, with the exact same data and 10 identical items will be created ... Do you completely defer the verification of the existence of a matching item to the "Storer" ? Therefor for each implementation (for example if I choose to store the data in a mongoldb or appengine) I should create all the methods to satisfy the Storer interface, including the verification of a matching item after a POST request before inserting it in the db. Am I right ?

Also, It is not obvious how to access to a resource item. /users/blablabla for example will get the users with which field of the schema matching blablabla? must it be named "id"? can we choose another name (for example userid, pseudo, alias or anything else that we can configure as the identifier) ? Because the automatically generated id (returned after a successful POST) might not be very aesthetic.

I am also willing to store some data, with basic mandatory information (example: user's id, password, email and name), a boolean (detailed) specifying if the optional fields have been provided and the values for the optional fields. For example, in a "details" subschema, I'd like the fields (gender, age, city) to be mandatory if detailed==true. This could occur in a 2step sign-in for example, letting the user choose if he wants to fill the optional information, but if he chooses to store the details then ALL of it should be provided.
If detailed==false those fields are optional, if detailed==true those fields are required. Is there a way to handle this without storing optional details and basic info in 2 independent resources ???? Or maybe just by putting this verification in the POST request handler Itself ...

**Comment by laahs** [comment]
Okay I found that the only field value that is required to be unique is the "id" field of a schema. It could be great to have a way to specify a name for the identifier. A consequence of only "id" field being required to be unique, 2 users with different id values but the same email address would be accepted as valid data ... in most cases this should be a conflictual situation ... I think it should be very useful to have a way to specify which fields must be unique without the need to handle this in a custom handler for each resource concerned by this kind of issue.

**Comment by rs** [comment]
There's two way to handle this:
1. Make use custom id generation function that would be a natural key for all the fields that must be unique in your object. This technique does work only if those fields are read only. It's generally the case for usernames for instance.
2. Use the underlaying database constraint system to ensure unicity.

I see no way from rest layer standpoint to enforce unicity on secondary fields.

**Comment by laahs** [comment]
1) I don't really understand what you mean by "the custom id generation function that would be a natural key". Is the custom id gen function a new feature (I don't see it referenced in the documentation) or are you simply advising me to create a function that would replace "OnInit:schema.NewID" for example? Because I don't get where to specify that.

2) the second option of using the underlaying database constraint system is probably the most obvious one ... 

about my question on having a field constrained by another field's value ... maybe is it what you designed "dependency" property of fields and "schema.Q" for ? using dependency can I specify detailed must be true if I want "gender" to be modified? Is the dependency check processed with the input data, or checking if the already stored version of the item fulfills the constraint?

**Comment by rs** [comment]
By custom id generation I mean a custom function to generate the id hooked on `OnInit` yes.

For `dependency` property, it should be what you are looking for. When set on a field, this field can't be changed until the schema query isn't met by the document. This query is performed on the document after all requested modifications has been performed on the document.
