### ISSUE TITLE
MultiGet calls onGot with nil item and no error.

### ISSUE THREAD

**Issue by smyrman** [rs/rest-layer#198]
https://github.com/rs/rest-layer/blob/48c11e50091e8c988780853a3aaa8af25cf98d42/resource/resource.go#L288.

MultiGet may call `onGot` with a nil item and nil error. If I adjust all my hooks to not only test for errors, but also for nil items, things work -- but is the current behavior intentional?

I am using latest master and the rest-layer-mongo backend.

**Comment by smyrman** [comment]
BTW, the `MultiGet` call will also return the nil items in it's list of items.

**Comment by rs** [comment]
>  // If one or more item(s) is not found, their slot in the response is set to nil.

Isn't it that case?

**Comment by smyrman** [comment]
That is in deed the case.

My question is if it's intentional to call the _hooks_ in this case (when the item isn't fond, and there is no error).

**Comment by rs** [comment]
Isn't the hook called too in the same condition on a simple `Get`?

**Comment by smyrman** [comment]
For Get`err` is set, so if you do a:
```go
func (hook Hook) OnGot(ctx context.Context, item **resource.Item, err *error) {
	if *err != nil {
		return
	}
	...
}
```
at the top, you are good (err would be resource.ErrNotFound in the case where the ID isn't found).

For MultiGet, you need to extend the check to:

```go
func (hook Hook) OnGot(ctx context.Context, item **resource.Item, err *error) {
	if *err != nil || *item == nil {
		return
	}
	...
}
```

Either way, I think it's fine. I am planning to go through all 0.2 labeled documentation, and do a larger update to the README. I will document it as it works now.

**Comment by rs** [comment]
Oh I see. Is your suggestion to set the error to `resource.ErrNotFound` in such case? That’d be fine with me.

**Comment by smyrman** [comment]
This was mainly raised as a question. I don't know what is best, so will leave it as is for now. We can revisit it later if relevant. Documentation for how to write hooks has been update in PR #201 to recommend:

```go
func (hook Hook) OnGot(ctx context.Context, item **resource.Item, err *error) {
	if *err != nil || *item == nil {
		return
	}
	...
}
```
