### ISSUE TITLE
File upload field?

### ISSUE THREAD

**Issue by tgirod** [rs/rest-layer#203]
Is there a way to handle file upload directly with rest-layer, or should I add an external endpoint to upload my file and then pass the URL to the uploaded content to my schema ?

**Comment by apuigsech** [comment]
Do you think it is necessary to have some type of Field that represents an entire file as part of REST layer? If yes, how do you think its behavior should be?

Regarding HTTP protocol, there are some reflections about it on that post; https://philsturgeon.uk/api/2016/01/04/http-rest-api-file-uploads/

And regarding the storage, should be file be stored on the storage backend (the database) or on filesystem having a reference to it on the storage backend?

**Comment by tgirod** [comment]
Fair enough, these are good points - it probably does not make sense to add a file upload field. Thanks for your insights!
