### ISSUE TITLE
Include new Storage Handler for SQL on the README

### ISSUE THREAD

**Issue by apuigsech** [rs/rest-layer#214]
I have created an Storage Handler for SQL databases using database/sql. It can be used with many different flavours of SQL databases, including SQLite.

In your list of supported Storage Handlers appears a SQLite3 that currently doesn't work and it's building SQL queries without  using prepared statetements (rising the risk of SQL injection vulnerabilities). I suggest to deprecate this one and include the one I did as a generic SQL.

Some tests are still pending, I'll work on that.

The link to my repo is; https://github.com/apuigsech/rest-layer-sql

**Comment by rs** [comment]
Can you please send a PR that add a link to your handler to the readme?

**Comment by Dragomir-Ivanov** [comment]
@apuigsech Congrats for the good work! Can I invite you to `#rest-layer` at `gophers.slack.com`.
Also, how is your code behaving on SQL injection attacks?

**Comment by apuigsech** [comment]
@Dragomir-Ivanov I am using Prepared Statements instead of concatenating strings, so it's SQL Injection safe.

**Comment by apuigsech** [comment]
Tests for translatePredicate are created, and also applied the @Dragomir-Ivanov suggestion. A PR to update your README is also done.
