### ISSUE TITLE
security problem when editing a subresource

### ISSUE THREAD

**Issue by tgirod** [rs/rest-layer#218]
Let's say we have two resources `users` and `posts`, and `posts` as a subresource of `users`.

`/users/alice/posts` will return the list of posts written by alice

`/users/alice/posts/post_id` will return something only if post_id exists AND alice owns that post, in the sense of the relation described with Bind

`POST /users/alice/posts/ body="my new post"` will create a new post, and automatically set the post's user to `alice`, which is really neat ! but then ...

`POST /users/alice/posts/ user="bob" body="impersonating bob"` will allow alice to create a post attributed to bob. the `user` gathered from the url (alice) will be discarded and replaced by the `user` gathered from the body of the request (bob).

I think this last behaviour is inconsistent with the previous examples, and a security issue. Here the variable gathered from the url should take precedence over the one passed as argument. or maybe, having both with different values should raise an error.

**Comment by smyrman** [comment]
Try to define the user Field on posts with `ReadOnly: true`. Path fields will ignore the Read-Only property, while your own fields will not.

**Comment by tgirod** [comment]
thanks @smyrman nice, you have solved my problem! Two remarks, though:

1. I still think the described behaviour is inconsistent, and I don't see a use case where that kind of impersonation is legit
2. There might be a use case where you want to be able to create a new post and define its `user` field - for example an admin creating a post under the name of another user. In that case you would bind the `post` schema to another endpoint, say `/posts` - but you wouldn't be able to set the user field because it is declared as readonly.

**Comment by smyrman** [comment]
1 - Consider `PATCH users/alice/posts/ user="bob"`. For posts it may be a bit werid, but if it was `PATCH users/alice/projects/ owner="bob"` then the transfer of ownership sounds like a legal operation to me.

>  I don't see a use case where that kind of impersonation is legit

In real-life cases, when creating a user `post`, I would have an `onInsert` hook that set the value from an user object in the (request) context, and still leave it as Read-Only.

For 2, I personally would not recommend rebinding the same resource against several end-points, as I feel it leaves a confusing API, but if you do, you need to choose a way to handle the edge-cases. Could be generating the schema with a helper function with fields set to ReadOnly based on function parameters, or could be something entirely different.

**Comment by tgirod** [comment]
Fair enough, thanks for your insight !

**Comment by smyrman** [comment]
I will close this issue now, but please feel free to report more issues as you find them. PRs for updating/improving the docs are also welcome.
