### ISSUE TITLE
Schema to JSONSchema

### ISSUE THREAD

**Issue by yanfali** [rs/rest-layer#22]
Is there any interest in auto-generating JSONSchema from schema? I have some stuff I would be willing to contribute upstream; it's incomplete and only covers by own use cases, but could easily be extended to handle more over time.

**Comment by rs** [comment]
Why not, let's see the PR. How far from a complet implementation with tests are you?

**Comment by yanfali** [comment]
Sounds good. It only covers basic JSON types at this time and I need to
invest some more time writing more complete tests. I'll try and get you
something by the end of the week.

**Comment by smyrman** [comment]
This seems to relate very closely to Issue #21. Does any of the suggestions there make sense for your contribution @yanfali ?

**Comment by yanfali** [comment]
Ah, I stopped reading after I saw swagger, my apologies. Yes I'm interested in the JSONSchema generation. My use case is API discovery using a URL convention.

I actually did a simple implementation that handles only the common use cases I have. It's completely separate from `schema` and doesn't require any changes to schema itself, it simply iterates over the schema data structures. Schema is well structured enough that it's trivial to convert into JSONSchema.

**Comment by smyrman** [comment]
Well, I suppose the issue comes if others define custom validators, or if you want to handle AllOff / AnyOff?

**Comment by yanfali** [comment]
Agreed, though the nice thing about schema is it's not encumbered by any of these orthogonal concerns and is fairly simple to understand; this is why I would lean towards it being a separate companion package that lived under schema or rest-layer.

**Comment by yanfali** [comment]
I'm getting ready to upstream my lib. It's more for discussion right now. Issues with it:

1. not as efficient as it could be
1. unit tests use a third party library (goconvey) - I will need to remove this dependency so that it's the same as upstream project

I will make a PR but the expectation is to get the code into a shape that's better for upstream and/or discuss not including it in schema but leaving it as a standalone 3rd party library.

**Comment by yanfali** [comment]
PR #30 with the expectation that this is *not* the final implementation.

**Comment by yanfali** [comment]
We can close this any time. Thanks.
