### ISSUE TITLE
JSON schema to schema

### ISSUE THREAD

**Issue by stevegore** [rs/rest-layer#229]
Hi, are there any plans to be able to import a JSON schema document and create a REST-layer schema object with it?

We have schemas already defined and would like to use that as the basis of our REST API.

**Comment by smyrman** [comment]
There are no such plans; there is a lot of details and business logic that can be expressed in rest-layer schemas, that are not trivial to parse from JSON Schema. There are also some direct incompatibilities, such as the way Dependencies are specified. You are of course welcome to write your own parser, or perhaps a code-generator, allowing for visual inspection and manual tweaking when necessary.

Longer term though, I am writing a proto-type for a new schema package in a separate [repo](https://github.com/searis/schema) to try out some new concept, and parsing from JSON Schema could very well be one of them. There is however no gurantee, and no timeframe for proto-type completion or potential merge back into rest-layer.

**Comment by smyrman** [comment]
I am going to close this issue.
