### ISSUE TITLE
Describing Arrays of Objects?

### ISSUE THREAD

**Issue by yanfali** [rs/rest-layer#23]
Hello, I'm struggling at the moment in trying to describe Arrays of 'object'. It's not obvious looking at the primitives how to do that. I have experimented with setting a `schema.Fields` with a Validator for type `schema.Array` and then using the `Field.Schema` to describe the object, but I'm not sure this would validate correctly. Ideally, what would be interesting is if I could set a `schema.Schema` on an `Array`, so one could see the hierarchy.

Would there be interest in taking a patch for `Array` that would let me nest a `Schema` within an `Array`. `Array` itself doesn't let you map key validation to value validation in an obvious way. perhaps this is a documentation issue?

Thanks for any guidance.

**Comment by rs** [comment]
With `schema.Array` you can set the `ValuesValidator` to any validator. You can set this to a `schema.Dict` to describe your sub-objects for instance. Isn't it what you need?

**Comment by yanfali** [comment]
I did try that, but it wasn't clear how to map the names to the values
validator. For example, if some fields are strings and some are number
wouldn't dict allow either to be valid in a particular dict?

**Comment by rs** [comment]
That's true, the `schema.Dict` validator doesn't let you specify specific validator for given keys. You may either improve it or create a more advanced dict validator for that. It would be great to have this feature in the core.

**Comment by yanfali** [comment]
OK, I put up a PR for you to digest, that could be one possible way to solve this problem. It heavily leverages the existing code and uses an embedded Schema instance. I'm not sure if this is the right approach, so I would love some feedback. Also if you could let me know what other things you might like to see in there I will do my best to add them.

**Comment by rs** [comment]
Can we say this issue is resolved?

**Comment by yanfali** [comment]
Absolutely
