### ISSUE TITLE
Calling `field.Compile` for `schema.Array` values?

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [rs/rest-layer#240]
Shouldn't we compile the whole field, for `schema.Array`. So, instead of:
```
func (v *Array) Compile(rc ReferenceChecker) (err error) {
	if c, ok := v.Values.Validator.(Compiler); ok {
		if err = c.Compile(rc); err != nil {
			return
		}
	}
	return
}
```
We do:
```
func (v *Array) Compile(rc ReferenceChecker) (err error) {
	return v.Values.Compile(rc)
}
```
This way, we will still call the `c.Compile`, as well make sure that `Values` is a pointer. This is important for `schema.Time`, because it compiles the `format` array(its `Compile` has pointer receiver), that is needed for its usage.

**Comment by smyrman** [comment]
God catch.
