### ISSUE TITLE
go module: cannot find module providing package testing/mem

### ISSUE THREAD

**Issue by tgirod** [rs/rest-layer#253]
In a folder with some code that works when compiled inside $GOPATH:

```.sh
$ go mod init oral
go: creating new go.mod: module oral
$ go get -u ./...
go: finding github.com/rs/rest-layer/resource/testing/mem latest
go: finding github.com/rs/rest-layer/rest latest
go: finding github.com/rs/rest-layer/schema latest
go: finding github.com/rs/rest-layer/resource latest
go: finding github.com/rs/rest-layer/resource/testing latest
go: finding golang.org/x/crypto/bcrypt latest
go: finding golang.org/x/crypto latest
build oral: cannot load github.com/rs/rest-layer/resource/testing/mem: cannot find module providing package github.com/rs/rest-layer/resource/testing/mem
```

Is there something to modify in github.com/rs/rest-layer/resource/testing/mem to make it go modules compatible?

**Comment by smyrman** [comment]
Sorry that there has been no response.

I am not sure what causes the issue you are seeing. You can try to ensure you are depending on the master version of rest-layer.

```
$ go get -u  github.com/rs/rest-layer@master
```

**Comment by MrSander** [comment]
I confirm that pointing to the master version solves the issue. Thank you!

**Comment by smyrman** [comment]
As v0.2 has been released some time ago, I am closing this issue.
