### ISSUE TITLE
OnInsert/OnUpdate hooks can modify the new resource item, Etag not recalculated

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [rs/rest-layer#255]
During POST/PUT/PATCH new resource item Etag generation is done in `item, err := resource.NewItem(doc)` from the document supplied from the request. However after that hooks will be applied, that may or may not modify this item further. Modifying the item in the hook, doesn't recalculate the Etag. 
One obvious solution suggested by @smyrman , is moving Etag calculation right before hitting the Store.

**Comment by smyrman** [comment]
Let's try to find a few problem cases, to see how they are handled by any given solution:

E.g. what happens if:
- A resource with an `updateAt` timestamp field is PATCHED with no changes. Is the resource (and hence the E-tag) updated?

**Comment by Dragomir-Ivanov** [comment]
Okay, if you are referring to the invisible `_updated` field, that is produced by `rest-layer` then no, it is not included in the Etag sum. 
```
func NewItem(payload map[string]interface{}) (*Item, error) {
	id, found := payload["id"]
	if !found {
		return nil, errors.New("Missing ID field")
	}
	etag, err := genEtag(payload)
	if err != nil {
		return nil, err
	}
	item := &Item{
		ID:      id,
		ETag:    etag,
		Updated: time.Now(),
		Payload: payload,
	}
	return item, nil
}
```
However if you are including your own:
`"updated": schema.UpdatedField,`, I am afraid it is modification.

**Comment by smyrman** [comment]
I am referring to when you include your own field; or indeed any other field that is _generated_ (by a field or resource hook) on update.

A possible solution for that is to abort an update if there are no E-tag changes after e.g. a patch is applied. This of course need to be _documented_. The next question is -- is there a case where this isn't what we would want?

Another important question is:
- Is it _important_ for a hook to get an updated/accurate E-tag?

**Comment by smyrman** [comment]
Example trade-off:

> However if you are including your own: `"updated": schema.UpdatedField,`, I am afraid it is a modification.

We can avoid this by aborting the update if there are no changes to a resource after a patch or put operation.

Trade-off: It won't be possible to _force_ resource updates (via hooks) by updating (without changing) a field value.

What ever we end up on, the solution must of course be documented. Writing the documentation will also be a good test for the solution; if we can't easily formulate the behaviour in words, probably our solution is too complex.

**Comment by Dragomir-Ivanov** [comment]
In my opinion, force update via HTTP call should be counted as "update" even if we don't change anything in the resource item. Think of `touch` semantics.

If one doesn't want that behavior, then he should make his own hook that can be executed last, that should expect all relevant fields, and if no changes there, he can just make `item=original` and revert all changes, including any "updatedAt" fields, etc.

Sadly we can't modify HTTP response from hooks, so in this case one can return 304.

**Comment by smyrman** [comment]
> In my opinion, force update via HTTP call should be counted as "update" even if we don't change anything in the resource item. Think of touch semantics.

OK, let's go with this for now then; it sounds easier to document.

The only feature I can think of where an early abort sounds useful, is for _list PATCH_ operations, but that isn't a feature that we currently got. We can revisit it at that point.

The remaining question is then, is there a case for updating the E-tag between each hook (e.g. to check for changes between original and item), or is updating of the E-tag right before storing the resource sufficient?

**Comment by Dragomir-Ivanov** [comment]
I think updating right before storing is just fine for now. Will make a PR today or tomorrow.
