### ISSUE TITLE
Documentation update Validator

### ISSUE THREAD

**Issue by yanfali** [rs/rest-layer#26]
So I recently discovered a little quirk about interfaces which wasn't obvious to me as a user of `rest-layer/schema`. When setting Field { Validator } the schema FieldValidators *must* be pointers otherwise the interface detection for Compile() does not work as expected. Interestingly the detection for the FieldValidator interface does. I'm not good enough at understanding go interfaces to understand why this is the case, but it would be good to document this someplace as it can lead to FieldValidator Compile functions, not being executed.

It could be related to this from fields.go, but I'm not strong enough at go's type system to understand exactly why.

```go
                if c, ok := f.Validator.(Compiler); ok {
                        if err := c.Compile(); err != nil {
                                return fmt.Errorf(": %v", err)
                        }
                }
```

**Comment by yanfali** [comment]
Interestingly it partially works if you send copies rather than pointers, but Compiles will not execute. I see in all the examples in the README.md you clearly use pointer addresses, but it would be good to make this clear in the documentation. Let me know if you'd like me to create a PR with some text to this effect under Field.Validator.

**Comment by rs** [comment]
A PR would be great.

**Comment by yanfali** [comment]
Closing as resolved.
