### ISSUE TITLE
schema.Compile() clarification

### ISSUE THREAD

**Issue by yanfali** [rs/rest-layer#28]
@rs I have a question about who invokes Compile if you use rs/rest-layer/schema outside of rs/rest-layer. Would it be accurate to say that when used in a standalone manner, all users of schema *must* invoke `Compile()` on schema.Schema instances to guarantee they are correctly initialized?

If this is the case I will probably send you a PR with a documentation update :)

**Comment by rs** [comment]
Yes, in this case it is your responsibility to call Compile before using the schema.

**Comment by yanfali** [comment]
PR #29 Thanks

**Comment by yanfali** [comment]
Closing as resolved.
