### ISSUE TITLE
[jsonschema] Support for schema.Dict

### ISSUE THREAD

**Issue by smyrman** [rs/rest-layer#33]
As suggested by @yanfali, I am adding tickets for how to extend the initial JSON Schema support to support more types. `schema.Dict` will get it's own ticket, as it's tricky enough to deserve so.
# Forward

`schema.Dict` should be encoded to the same JSON type as `schema.Object` (object), but rely on `additionalProperties` when a  `KeysValidator` is not set or `patternProperties` if `KeyValidator` _is_ set.

According to the validaiton spec [section 5.4.4](http://json-schema.org/latest/json-schema-validation.html#anchor64), `aditionalProperties` can either be a boolen, in which case any value is allowed when it's `true`, or a JSON Schema, in which case the values must apply to that schema. `patternProperties`  must be an object with regex as keys, and JSON Schemas as values.

However, as far as I can see from the examples, as well as from the [Core/Validation Meta-Schema](http://json-schema.org/schema), there are no required elements in a JSON Schema object, which means it can be left emty in order to allow for all types (similar to the empty `interface{}` in go ).
# Expected result

This really cumulates to us wanting to end up with the following.

If neither`KeyValidator` nor `ValueValidator` is set:

``` json
"type": "object",
"additionalProperties": true
```

If only `ValueValidator` is set:

``` json
"type": "object",
"additionalProperties": {/* JSON Schema from validatorToJSONSchema(ValuesValidator) */}
```

If only `KeyValidator` is set:

``` json
"type": "object",
"patternProperties": {
    "<regex from KeyValidator>": {}
}
```

If both `KeyValidator` and `ValueValidator` is set

``` json
"type": "object",
"patternProperties": {
    "<regex from KeyValidator>": {/* JSON Schema from validatorToJSONSchema(ValuesValidator) */}
}
```

**Comment by rs** [comment]
Isn't this already fixed with `schema.Object`?

**Comment by smyrman** [comment]
No, schema.Dict is not yet handled. The most tricky part will be to handle the key validatior, as it's likely that we can only handle it properly if it's the builtin string type and uses regex (or something we canvert to regex).

There is plans in JSON Schema to support something more than just "patternProperties", but that's not ready yet:
https://github.com/json-schema-org/json-schema-spec/issues/117

**Comment by smyrman** [comment]
I will start looking at an implementation for this issue.
