### ISSUE TITLE
Validate a field based on the value of another field ?

### ISSUE THREAD

**Issue by howesteve** [rs/rest-layer#37]
Hello,

I was wondering how to validate a field based on the value of another field; ex: 

{"doc": {"type": "x", "value": "xxxxx"}}
{"doc": {"type": "y", "value": "yyy-yyy"}}

if doc type is "x", allowed value format is "xxxxx"; if it's "y", allowed value format is "yyy-yyy".

Currently, validators seem to be for a single value only. What is the best way to do it ?

Thanks.

**Comment by smyrman** [comment]
Hi, I am not part of this project, but I though I might try to help you out anyway.

From the documentation, I would assume the following should work:
```go
var s := schema.Schema{
	Fields: {
		"doc": schema.AnyOf{
			schema.Object{Schema: schemaX}, // where schemaX defines type == x and value of format "xxxxx"
			schema.Object{Schema: schemaY}, // where schemaY defines type == y and value of format "yyy-yyy"
		},
 	},
}
```
If you have some fields you need to have common in addition to the ones you mention, you could perhaps try:

```go
var s := schema.Schema{
	Fields: {
		"doc": schema.AllOf{
			schema.Object{Schema: commonSchema},
			schema.AnyOf{
				schema.Object{Schema: schemaX},
				schema.Object{Schema: schemaY},
			}
		}
 	}
}
```

**Comment by howesteve** [comment]
Thank you, I'll try that option.

**Comment by smyrman** [comment]
@rs , can this be closed?
