### ISSUE TITLE
Informational:  SQLite storage backend

### ISSUE THREAD

**Issue by jxstanford** [rs/rest-layer#4]
Just wanted to let you know that I pushed a SQLite3 backend here:  https://github.com/jxstanford/rest-layer-sqlite3.  It's not on your list of targets, but thought it might be of interest.  It's my first golang project, so I'm sure there there is room for idiomatic and logic improvements, so I'm happy to consider any feedback.

**Comment by rs** [comment]
That's great!

Here are some suggestions:

- How is it sqlite3 specific? Thanks to `database/sql`, your storer seems generic and may apply for any SQL driver implementing the `database/sql` interface. Am I wrong?
- I would not add a dependency on logrus. If you want to expose a logging feature, you may define a logging interface for your logger the user could implement and assign to your storer. BTW I will add http://github.com/rs/xlog to rest-layer as soon as I have some time. When done, you will be able to get a logger shared with the rest-layer app from the context.

**Comment by rs** [comment]
I didn't resist to implement xlog (and xhandler in general). See https://github.com/rs/rest-layer/blob/master/README.md#logging.

**Comment by jxstanford** [comment]
Thanks for the logging, I'll change mine over.  

Regarding generic SQL vs SQLite3, I thought about that, and will work toward a generic solution.  I was a little nervous about possible differences in SQL statement construction between databases, and wanted to get a working version first.  Thanks for the feedback!

**Comment by rs** [comment]
No problem. Do not hesitate to make a PR to add you project in the rest-layer README when you feel ready.
