### ISSUE TITLE
JSONSchema required

### ISSUE THREAD

**Issue by yanfali** [rs/rest-layer#40]
When schema is embedded within an Array or an Object Field the required field is being added to the "items" or "properties" body. This should appear one level up at the same level as "type"
Reported by @smyrman

Example of incorrect output

```
        "items": {
          "properties": {
            "key": {
              "type": "string"
            },
            "score": {
              "type": "integer"
            },
            "required": [
              "score",
              "key",
              "value"
            ],
            "value": {
              "type": "string"
            }
          },
          "type": "object"
        },
```

Example of correct output

```
        "items": {
          "properties": {
            "key": {
              "type": "string"
            },
            "score": {
              "type": "integer"
            },

            "value": {
              "type": "string"
            }
          },
          "required": [
            "score",
            "key",
            "value"
          ],
          "type": "object"
        },
```

**Comment by yanfali** [comment]
@rs I'll try and work up a patch, I have an idea of how to solve this.

**Comment by yanfali** [comment]
@smyrman you might want to take a look now. I think it does the right thing. It's definitely generating valid JSON.

**Comment by smyrman** [comment]
From what little testing I could do, it looks fine, at least inside an items clause.

**Comment by smyrman** [comment]
@rs, @yanfali, I assume this issue should be closed.
