### ISSUE TITLE
[jsonschema] Table driven tests

### ISSUE THREAD

**Issue by smyrman** [rs/rest-layer#44]
Hi.

I am interested in contributing some table driven tests for the `jsonschema` package. I am picturing an array of schema definitions that can be compared to a JSON string via [asserts.JSONEq](https://godoc.org/github.com/stretchr/testify/assert#JSONEq). I would expect my progress to be a bit slow, as it's a busy period for me familywise.

@rs, is depending on Go 1.7 sub-tests (inside the test package only) OK, or should I write my tests so they work for Go 1.6?

@yanfali, I though I would mention your name as well so you get notified ;-)

**Comment by rs** [comment]
Go for 1.7 only, just add a build flags so it won't break 1.6 CI.

**Comment by smyrman** [comment]
Started of with some simple cleanups first in #45. @yanfali, are you also happy with these?

**Comment by smyrman** [comment]
> Go for 1.7 only, just add a build flags so it won't break 1.6 CI.

Actually, when I started coding, I found it was easy enough to support both (via build tags) -- I will use parallel sub-tests for Go 1.7 and a sequential approach without sub-tests for Go < 1.7.

My initial work lives on [this branch](https://github.com/smyrman/rest-layer/tree/table-tests).

It's based on top of #45. I will push it to a PR soonish.

**Comment by smyrman** [comment]
Initial review for table-tests added in #46. @rs, when you have time, let me know if this is moving in the right direction, and what you would like to change.

**Comment by yanfali** [comment]
I thought this was merged. I used the pattern recently in one of my projects.

**Comment by smyrman** [comment]
I didn't convert all the jsonschema test, but yeah, I think we can close it.

**Comment by rs** [comment]
Kind of unrelated, but shouldn’t we move all the jsonschema tests inside the package?

**Comment by smyrman** [comment]
Sounds sensible

**Comment by smyrman** [comment]
>  shouldn’t we move all the jsonschema tests inside the package?

@rs, I am now doing this in #64. This commit also moves the remaining tests into table tests when appropriate.
