### ISSUE TITLE
JWT-auth example allway fails

### ISSUE THREAD

**Issue by xuuz** [rs/rest-layer#48]
Hello,

I'm trying to play with jwt-auth example, but it's allway got errors, Could you please help me this point? Thanks alot !

$ http :8080/posts access_token==eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiamFjayJ9.i74uQMaftKhwZri0XaTMTnqiBY0cmuMu27Yuv8WUy68 title="Jack's post"
HTTP/1.1 422 Unprocessable Entity
Content-Length: 82
Content-Type: application/json
Date: Sat, 12 Nov 2016 11:30:07 GMT

{
    "code": 422, 
    "issues": {
        "user": [
            "required"
        ]
    }, 
    "message": "Document contains error(s)"
}

**Another tests:**
http :8080/posts access_token==eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiamFjayJ9.i74uQMaftKhwZri0XaTMTnqiBY0cmuMu27Yuv8WUy68
HTTP/1.1 401 Unauthorized
Content-Length: 37
Content-Type: application/json
Date: Sat, 12 Nov 2016 11:35:21 GMT

{
    "code": 401, 
    "message": "Unauthorized"
}

**Here is the example console:**

go run jwt-auth.go 
2016/11/12 18:21:55 Serving API on http://localhost:8080
2016/11/12 18:21:55 jackTokenString==%!(EXTRA string=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiamFjayJ9.i74uQMaftKhwZri0XaTMTnqiBY0cmuMu27Yuv8WUy68)
2016/11/12 18:21:55 johnTokenString==%!(EXTRA string=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiam9obiJ9.yrpLD2gUq_TIyxMKpDBHQO391KGCNrFl-RvMT-p90MU)
2016/11/12 18:21:55 Your token secret is "secret", change it with the `-jwt-secret' flag
2016/11/12 18:21:55 Play with tokens:

- http :8080/posts access_token==eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiam9obiJ9.yrpLD2gUq_TIyxMKpDBHQO391KGCNrFl-RvMT-p90MU title="John's post"
- http :8080/posts access_token==eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiam9obiJ9.yrpLD2gUq_TIyxMKpDBHQO391KGCNrFl-RvMT-p90MU
- http :8080/posts

- http :8080/posts access_token==eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiamFjayJ9.i74uQMaftKhwZri0XaTMTnqiBY0cmuMu27Yuv8WUy68 title="Jack's post"
- http :8080/posts access_token==eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiamFjayJ9.i74uQMaftKhwZri0XaTMTnqiBY0cmuMu27Yuv8WUy68
value: <nil>
value: <nil>
value: <nil>
value: <nil>
value: <nil>
value: <nil>

**Comment by omani** [comment]
same here. maybe I can figure out why. others are welcome to have a look into this.

**Comment by omani** [comment]
thank you.
