### ISSUE TITLE
Are there any plans to implement swagger?

### ISSUE THREAD

**Issue by omani** [rs/rest-layer#53]
Hi all,

first of all thank you for this wonderful piece of software.

I want to ask if there is any plan to implement or provide a swagger overlay.

**Comment by rs** [comment]
We have JSON Schema implemented already. Ping @smyrman for more info on how it could be used for Swagger.

**Comment by omani** [comment]
hi @smyrman,

any idea how the json schema could be used for swagger?

**Comment by smyrman** [comment]
@omani, Swagger 2.0 uses a subset of the JSON Schema Draft4 specification to describe [Data Types](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types).

Therefore, the JSON Schema support in rest-layer will eventually make it possible to describe the leagal/expected payload per API endpoint.  Please note that the JSON Schema support in rest-layer is still under development, and doesn't yet handle all schema.Validator types nor support custom validators.

**Comment by smyrman** [comment]
Also please note that no work has started on actually implementing Swagger API documentaiton support, which I assume would involve translating  a [resource.Index](https://godoc.org/github.com/rs/rest-layer/resource#Index) into a Swagger 2.0 JSON document

By active use of hardcoding, you might be able to do this in a crude way for your current rest-layer based project, and then call into the JSONSchema API for Data Type generation.

Other than that, I assume PRs are welcome:-)

**Comment by smyrman** [comment]
> @omani, Swagger 2.0 uses a subset of the JSON Schema Draft4 specification to describe Data Types.

I was actually mening to refer to [definition objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#definitionsObject). Sorry about that.

**Comment by smyrman** [comment]
There is a new version called [OpenAPI Specification 3.0.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md).

I have been able to generate such a file in part from `resource.Index`, and validate that it works with the latest Swagger UI. There is however a lot of hard-coding, and there are few things that should probably be changed in the `resource` package to support it better.

I don't have time to clean it up and contribute it back into a propper PR right now, but I can dump it on a branch in case anyone else want to have a look. I will try to do this in not to long...

**Comment by smyrman** [comment]
Here is what we have (pretty limited/hard-coded, and influenced by #127 being open):
- https://gist.github.com/smyrman/a0a015f5763f98343d23afcef8b9a0f8

Example usage in an application atm. (where `API` is a custom struct holding a `resource.Index` and some other relevant meta information):
```go
// NewDocHandler returns a handler that writes an "openapi.json" file to the
// response, which could be used for documentation UIs.
func (api *API) NewDocHandler() (http.Handler, error) {
	api.ensureIndex()

	doc, err := openapi.RestlayerDoc(openapi.Info{
		Title:       "My Awesome APII",
		Description: "Allows access to awesome resources.",
		Version:     "0.0.1",
	}, api.index)
	if err != nil {
		return nil, err
	}

	doc.Servers = []openapi.Server{
		{URL: api.RootURL},
	}

	doc.Components.SecuritySchemes = map[string]json.RawMessage{
		"jwt": openapi.SecuritySchemeJWT,
	}

	doc.Security = []openapi.SecurityRequirement{
		{"jwt": []string{}},
	}

	return openapi.NewHandler(doc)
}
```

A proper implementation for rest-layer should probably rely more on `schema.Schema` usage over `json.RawMessage` and other values for all schema definitions, and encode the schema as part of a `MarshallJSON` implementation.

**Comment by apuigsech** [comment]
@smyrman work looks great as prototype. 
Is there any progress regarding this? Should I use @smyrman work as staring point?

**Comment by smyrman** [comment]
What I have is a bit hard-coded here and there, but we are using it for our own APIs and it works. Make sure all custom `FieldValidator` implementations implement the `jsonschema.Builder` interface, or it will error hard.

For any official Swagger support, I think it's pretty far away atm.

**Comment by smyrman** [comment]
>  but we are using it for our own APIs and it works

Probably we are not using the _exact_ same version that is in the gist btw... But just scream out (perhaps on slack) if you have any issues using it. Look for `#rest-layer` on  Gopher Slack

**Comment by apuigsech** [comment]
Based on @smyrman's work I created the [rest-layer-openapi](https://github.com/apuigsech/rest-layer-openapi) with some improvements;

- I am using [kin-openapi](github.com/getkin/kin-openapi/openapi3) data model instead of a build in.
- I did some improvements on the OperationIDs, now if it is a sub-resource adds a suffix, for instance; _GetPostsOnUser_.

There is still some pending work, specially on supporting more Field types and create some documentation and examples, but I think it's quite solid.

An example of usage is;

```
	// Generate index and bind resources and sub-resources.
	index := resource.NewIndex()
	users := index.Bind("users", user, mem.NewHandler(), resource.Conf{
		AllowedModes: resource.ReadWrite,
	})
	users.Bind("posts", "user", post, mem.NewHandler(), resource.Conf{
		AllowedModes: resource.ReadWrite,
	})

	// Generate openapi3 document.
	doc := openapi.NewOpenapiFromIndex(index, openapi3.Info{
		Title:   " myAPI",
		Version: "1.0",
	})

	// Print openapi3 document in JSON format.
	b, _ := doc.MarshalJSON()
	fmt.Println(string(b))


```

**Comment by smyrman** [comment]
Will close this question.

**Comment by Dragomir-Ivanov** [comment]
@smyrman Shouldn't we mention somewhere in the README that [rest-layer-openapi](https://github.com/apuigsech/rest-layer-openapi) exists?

**Comment by smyrman** [comment]
Yes, that's probably a good idea. I am not quite confident our generated JSON-schema is a 100% valid with OpenAPI though, so we should be aware of that.

**Comment by Dragomir-Ivanov** [comment]
Yes, we can decorate the link with `EXPERIMENTAL`/`ALPHA` tag.
