### ISSUE TITLE
Support for GridFS

### ISSUE THREAD

**Issue by omani** [rs/rest-layer#54]
hi @rs,

are there any plans to implement gridfs and use it like it can be used in python-eve (schema validator "media" for example)?

**Comment by rs** [comment]
I have no plan to implement it but PRs are welcome.

**Comment by omani** [comment]
ok eventually I will come up with a PR.

**Comment by omani** [comment]
hi @rs,

I modified the code a little bit and I would like to hear some suggestions.

is this going in the right direction?
https://github.com/omani/rest-layer-mongo/commit/1a1e88f58903a2aecdbe50b12ad532c2fc63d331

**Comment by omani** [comment]
for now I am giving up on this since it requires modifications in multiple places.

>eventually I will come up with a PR.
