### ISSUE TITLE
Can we make ETAG presence in PATCH/PUT/DELETE requests mandatory?

### ISSUE THREAD

**Issue by omani** [rs/rest-layer#58]
from the docs:
>Concurrency control header If-Match can be used with all mutation methods on item URLs: PATCH (update), PUT (replace) and DELETE (delete).

I would argue to make the `If-Match` header mandatory for all the above three http methods so it is ensured that concurrency control is taking place. By forcing the client to use the conditional requests (with an `If-Match` header) you embrace the fact that the backend does indeed concurrency control. Allowing a client to opt out of this could result in unexpected behavour when modifying a resource.

**Comment by rs** [comment]
Even without if-match the backend will ensure concurrency control at backend level. This header is made available for when you want and can manage this concurrency up to the app level.
