### ISSUE TITLE
Question: Custom routes

### ISSUE THREAD

**Issue by omani** [rs/rest-layer#67]
Hi,

if I want to enjoy all the benefits of rest-layer (data validation, json endec, hooks, etc.) but don't want to actually work with the underlying storage backend. how would I do it?

I came up with the idea of using the mem storage so I can bind a route. it works but it is ugly.

Are there any plans to make custom routing available? at the end it is just an index.Bind() without a storage handler. Or any other hints?

**Comment by smyrman** [comment]
rest-layer proclaims itself as an opinionated framework, but you could use only the parts of rest-layer that you need, without using the whole package.

You could for instance rely on the `rest-layer/schema` package only. This gives you the data validation capabilities, and you can implement your own logic to route views, fetch dat etc..

If you do need the `rest-layer/resource`, and or `rest-layer/rest` as well, then perhaps it would still be best for you to provide your own implementation/adapter for the [Storer interface](http://rest-layer.io/#data-storage-handler).

**Comment by omani** [comment]
my use case is a login route for providing (creating) a JWT (token). as the example auth-jwt says, one has to implement an own login mechanism to handle the creating of a json web token.

and I did that with using "login" as my route in index.Bind() and using the mem storage (mem.NewHandler()) as a pseudo db. but don't need it really since all the logic is in a OnInsert hook for this route.

**Comment by omani** [comment]
I thought of something like an abstraction layer like:

index.Router(...) which gets a handler. just like an http handlerfunc. but with all the benefits of rest-layer.

**Comment by rs** [comment]
A storage handler is a CRUDL version of a http handler. You could actually create a storage handler instead of using `OnInsert`.

Could you show use some of you code you produced to handle JWT? It may be a good way for us to think about easier ways to handle this kind of cases.

**Comment by omani** [comment]
I am using the example `auth-jwt`.

or do you mean the creation of jwt? (login)

**Comment by omani** [comment]
>A storage handler is a CRUDL version of a http handler. You could actually create a storage handler instead of using OnInsert.

now that you say that the storage handler is nothing else than a CRUDL version of a http handler it just clicked in my brain. you are right. the storage handler is meant to be used for such cases.

and now that you say it, I think a better name for a storage handler would be a CRUD handler. maybe it makes sense to rename `Storer`?

**Comment by smyrman** [comment]
> I think a better name for a storage handler would be a CRUDL handler. maybe it makes sense to rename Storer?

I don't think that renaming the interface is a good idea. The main use case for implementing a Storer is still to provide data storage.

If you feel the documentation should be updated to mention CRUDL, that's probably possible, although it should be obvious enough that this is what it is from the list of methods.

**Comment by rs** [comment]
We may also provide some examples of such usage.

**Comment by omani** [comment]
Ok. I think I will rewrite my login route with a new storage handler. thanks.
