### ISSUE TITLE
Feature request: have total items in response

### ISSUE THREAD

**Issue by omani** [rs/rest-layer#68]
Hi,

as previously discussed in a PR. I would like to ask how and when do we implement the feature of having `Total` items being displayed in the response? @rs said it should be explicitly requested, so my question is, are there any plans how to do it?

**Comment by rs** [comment]
We have to define the way we request it and how to query the storage layer.

I would propose a query-string parameter like `total=1` (no sure about the naming though) and an optional interface on storer with the method `Count`. If `total` is `1`, the storer implement this `Counter` interface and the returned `Total` is -1, rest-layer would then call the `Count` method to fill this metadata in the response.

cc @smyrman

**Comment by smyrman** [comment]
@rs, I think that proposal is reasonable, but I will list one more.

If it is not necessary to decide this at request time, I.e. the `total=1/0` rest parametre is not needed, I also have an alternative solution:

Backends that don't have an efficient way of doing the total count together with the query, could offer an additional Storer implementation with the suffix `WithTotal`. If this is not done, the end-user could implament his own `Storer` wrapper (e.get. using struct inheritance) that does am additional count queryour as part of `Find()`.

**Comment by smyrman** [comment]
So, basically it boils down to weather includingelin the `total` count should be a server side or client side decision... Are there cases where an additional count query, e.g. for large MySQL tables, could lead to server side lockups or worse?

There could also be that there are other good usecase for the `Counter` interface to be added, unrelated to this feature. I don't foresee any at this point, but it's possible...

**Comment by rs** [comment]
I don't understand the different between your proposal and mine @smyrman. Did I miss something?

**Comment by smyrman** [comment]
@rs ,  the alternative proposal does not include adding a new optional interface.

**Comment by rs** [comment]
When the database is not able to compute the total efficiently at query time, you can't predict the complexity of this query. When filters are involved and indexes don't cover the whole query, counting may be more expensive than the *paged* query itself.

So my goal is to offer possibility to the client to only request this total when it is wanted.

**Comment by smyrman** [comment]
> So my goal is to offer possibility to the client to only request this total when it is wanted.

If the clients should make this call, it's fine, then the alternative one don't work. My angle was (potentially third-party) clients forcing the server to a hault by generating count queries that never complete, and possibly don't get killed when the request times out. In this case it sounds reasonable to be able to disable total=1 server side. With your proposal, I was _picturing_ that all supported storage engines would implement the optional Counter interface, but of course that does not need to be the case here.

**Comment by rs** [comment]
We could also disable this feature in binding config.

**Comment by smyrman** [comment]
> We could also disable this feature in binding config.

Yes, that would work. However this new options also adds complexity, which is why I wanted to list an alternative, in case it was good enough.

I think the alternative solution has slightly less complexity, as there is no new optional interface to document, and no new bind config. The drawback of it we have already considered: clients can't opt in our out for getting total: the server decides (per resource) via bind.

**Comment by omani** [comment]
yes I like this proposal. enable/disable in binding and if enabled, client decides if it wants a total.

**Comment by smyrman** [comment]
Come to think of it, the `WithTotal` don't actually need to be a separerte `Storer` implementation neither; it could just be a second initializer for the same implementation.

Anyway, have a think about if and go with the solution you prefer.

**Comment by rs** [comment]
Please review #69, feedback welcome.
