### ISSUE TITLE
Question: Approach to pass custom parameters to my Google Datastore handler

### ISSUE THREAD

**Issue by ajcrowe** [rs/rest-layer#72]
I've largely completed a Google Cloud Datastore handler, see https://github.com/ajcrowe/rest-layer-datastore

However I would like to be able to control whether a field is indexed within Datastore for each Field. What approach would you recommend for this? 

Perhaps extending Field to have a StorageOptions param which can be `schema.StorageOptions` which is a `map[string]interface{}`?

Like this?

```go

type StorageOptions map[string]interface{}

user = schema.Schema{
		Description: `Represents a user`,
		Fields: schema.Fields{
			"id":      schema.IDField,
			"created": schema.CreatedField,
			"updated": schema.UpdatedField,
			"name": {
				Required:   true,
				Filterable: true,
				Sortable:   true,
				Validator: &schema.String{
					MaxLen: 150,
				},
				StorageOptions: &schema.StorageOptions{
					"index": false,
				},
			},
...
```

Wanted to check this approach.

**Comment by rs** [comment]
My opinion on that is that the application should not manage indexes. This is something that should be manage by operations. You don't want your app to randomly trigger index creation in your back on a system in production.

**Comment by ajcrowe** [comment]
This is something which is set per property of each entity in Datastore and defaults to being on, however for certain fields (like a description) it's recommended for it to be disabled.

I'm not sure how this could be achieved currently as this indexing option is set when you create each entity's property.

You could in theory read and modify each entity after creation and disabled indexing for each specific field after the fact but this seems wrong.

**Comment by rs** [comment]
I'm not familiar with Datastore. Is an entity a form of collection? If so, can't you create your entities in advance with the right settings instead of letting the app doing it?

**Comment by ajcrowe** [comment]
No the entities are of a "kind" which can have completely dynamic schema, so each entity can have completely independent fields I believe.

So the time to set indexing is when you create the entity, the library allows you to set this with a tag on your structs as `datastore:,noindex` or on a `datastore.Property` with the `NoIndex` field.

**Comment by rs** [comment]
Would it make sense to pass a list of fields to index (or not) at init of the storer?

**Comment by ajcrowe** [comment]
That could work, thanks for the suggestion. Maybe extend `NewHandler` to accept a `[]string` which fields to disable indexing on.

Be nice to have this somehow defined in the schema but this seems the path of least resistance.

**Comment by rs** [comment]
We may think about adding an index info field in the schema that could be used (or not) by storage handlers. We have to come with a way to express index configuration that would work for all kinds storage handlers.

**Comment by ajcrowe** [comment]
Going to close this now I've added this feature on handler creation. Thanks for the advice.
