### ISSUE TITLE
Provide: mongo's $regex query parameter

### ISSUE THREAD

**Issue by omani** [rs/rest-layer#73]
It would be awesome to be able to query a value of a field by regex.

Since the format of the parameter is inspired by the mongodb query format we could also have its $regex in queries.

**Comment by omani** [comment]
feedback is welcome.

**Comment by rs** [comment]
The problem with `$regex` is that not only all storer won't be able to support it (they should return `ErrNotImplemented`) but some storage engines may only support of subset of the regexp features.

**Comment by omani** [comment]
but this shouldnt stop us from implementing this, right? Those Storers which can only support a subset of regex can tell so and provide only those. I see mongodb as the storage for restful api anyway. any other storer can choose to opt out. (ErrNotImplemented).

**Comment by rs** [comment]
Yes you are right.
