### ISSUE TITLE
Question: Getting another document from a hook

### ISSUE THREAD

**Issue by 0xef53** [rs/rest-layer#75]
Hello there.

I would like to ask your advice in the following task.

Before adding a new document to a MongoDB (via POST method) I need to calculate some of its fields' values. In order to do that I need to get another two documents from another collection (all collections are handled by the same app).

I seems to me that `InsertEventHandler` hook will come in handy here. But it's not clear to me how use it properly in that task. Might it be the `http.NewRequest` ?

Thanks in advance.

**Comment by rs** [comment]
You can access the `resource.Index` (the router) from your handler. This part is not documented, but the `resource.Index` is stored in the context here: https://github.com/rs/rest-layer/blob/master/rest/handler.go#L63.

From the index you can access any other resources using `GetResource` for instance, and perform internal queries on it. One example of such sub-request can be found here: https://github.com/rs/rest-layer/blob/master/rest/util.go#L186.

**Comment by 0xef53** [comment]
Thanks a lot !
