### ISSUE TITLE
Feature: Make custom HTTP methods

### ISSUE THREAD

**Issue by omani** [rs/rest-layer#81]
Hi,

it would be super awesome to be able to create or have custom http verbs (methods) so I can be more flexible with my own storage handler (`Storer`).

Something like
```
curl -XOPEN /api/some/route/to/media/file
curl -XBAN /api/some/route/to/bridge/ip
curl -XDELEGATE /api/some/route/to/proxy/zone
```

can we implement this or any plans to make this happen?

**Comment by rs** [comment]
Not really. The whole idea is to abstract the rest layer from the storage layer. Thanks to that you can swap the rest layer for the GraphQL layer with no change on your storage layer.

You can write a custom layer to replace rest and reuse the resource package with the same storers if you want.

**Comment by smyrman** [comment]
I think most REST-APIs tend to be CRUD of CRUDL, like rest-layer.

That means that if you want to DELEGATE a proxy/zone, you do so with a -Xbox PATCH where you e.get. change the state and assign something, and install am appropriate hook.

I don't know what use case you are considering, but if you want custom methods (that perhaps even take parameters), perhaps you want too look into RPC frameworks, e.g. https://capnproto.org/ or http://www.grpc.io/?

**Comment by omani** [comment]
yeah I could work with hooks, a custom layer and the like. I just thought it would be far easier to implement new features of my own rest API by defining new http methods and attach the appropriate function to them.

but you both are right, it's not the way rest should be used. in rest terms. that's why your suggestion with grpc makes sense to me.

I can work with queries and/or hooks. thanks guys.
