### ISSUE TITLE
Question : How do you handle pages for different routes

### ISSUE THREAD

**Issue by xydac** [rs/rest-layer#82]
Here's the scenario :
Consider i want to have  a path called "/Pages" and i want to attach it to multiple other routes so how do i create reference so i can use a single Page type and use it for different routes as below

```

/foo/pages/...
/bar/pages/...
/foobar/pages/...
```

I do want to use the same type called "Page" instead of defining it again and again for different routes.

**Comment by smyrman** [comment]
Did you try to bind the same resource to multiple indices?

```go
foo := resource.NewIndex()
bar := resource.NewIndex()
foo.Bind("pages", pages, mem.NewHandler(), resource.Conf{AllowedModes: resource.ReadWrite})
bar.Bind("pages", pages, mem.NewHandler(), resource.Conf{AllowedModes: resource.ReadWrite})

apiFoo, err = resource.NewHandler(foo)
// handle error
http.Handle("/foo/", http.StripPrefix("/foo/", apiFoo))

apiBar, err = resource.NewHandler(bar)
// handle error
http.Handle("/bar/", http.StripPrefix("/bar/", apiBar))
...
```

If you instead want pages to appear as a filtered sub-resource to another resource, have a look at http://rest-layer.io/#sub-resources

**Comment by xydac** [comment]
I did't try this but how will i define the schema in this case:

```
pages = schema.Schema{
        Description: `Represents a page`,
        Fields: schema.Fields{
           "user": {
                Required:   true,
                Filterable: true,
                Validator: &schema.Reference{
                    Path: "foo",//<-- How do i handle this for foo and bar in same schema
                },
            }
```

**Comment by smyrman** [comment]
I don't know if you can refer to anything outside of your current index. Do you think you could perhaps elaborate a bit more on your use-case? Why do you need to include the same schema on different paths? And are they meant to link to the same storage (I.e. table in SQL or the same collection in Mongodb terms)? And what is the m2m link going to achieve?

**Comment by xydac** [comment]
I was finally able to do it what i needed.

Basically what i wanted was to keep the rest of the schema for pages as common and the reference field to change between different types.

So that I can add new field to Page and it should work without altering the code for Foo/Bar/Foobar

The way i did this is dynamically adding the referenced field user 

```

p := getPageModal() // This is where i get the generic Page object that i can use for Foo/Bar...
p.Fields["user"]=Schema.Field{
                Required:   true,
                Filterable: true,
                Validator: &schema.Reference{
                    Path: "users",
                },
            }
// Then Added the binding
users.Bind("posts", "user", p, mem.NewHandler(), resource.Conf{ AllowedModes: []resource.Mode{resource.Read, resource.List,resource.Create, resource.Delete},})

```
