### ISSUE TITLE
How do I use rest-layer with gorilla mux?

### ISSUE THREAD

**Issue by omani** [rs/rest-layer#83]
I want to use gorilla mux for my other routes so I can filter on methods and hostnames etc. Just what gorilla mux offers in general. Now with the below setup my rest-layer API does not work. I get NOT FOUND back. but my other routes do work.

```go
r := mux.NewRouter()
r.HandleFunc("/me", getMe(jwtSecretBytes))
r.HandleFunc("/websocket", serveHome)
r.Handle("/files", gridfsapi)
r.Handle("/", c.Then(api))

log.Println(fmt.Sprintf("Serving API on http://localhost:%d", port))

if err := http.ListenAndServe(fmt.Sprintf(":%d", port), r); err != nil {
	log.Fatal(err)
}
```

Shouldn't `api` which is just a `rest.NewHandler(index)` work with gorilla mux?

**Comment by rs** [comment]
Yes it should work. Doesn't it?

**Comment by omani** [comment]
no it doesn't. Can you reproduce it with gorilla mux?

**Comment by smyrman** [comment]
Disclaimer: haven't looked at Gorilla in years.

But does Gorilla mux `Router.Handle` handle sub-paths when there are no parameters in the match string?   Golangs built-in http mux handled sub-routes if the path string ends with a slash but I thought Gorilla Mux didn't.

Do you need to use https://godoc.org/github.com/gorilla/mux#Route.PathPrefix?

**Comment by omani** [comment]
yes. the pathprefix solved it.

```go
r.PathPrefix("/api/").Handler(http.StripPrefix("/api/", api))
```

thank you very much.
