### ISSUE TITLE
Feature Request: Provide Unique Field Definition

### ISSUE THREAD

**Issue by omani** [rs/rest-layer#86]
with a boolean field definition named "Unique" we could avoid the need for a hook just to make sure the provided field (name, position, whatever....or something which is supposed to be unique) is not already in the db.

this would result in much less code (no hook needed).

are there any plans to implement this?

**Comment by rs** [comment]
We can not guarantee unicity at this layer. Nothing prevents another client from adding a document breaking the unicity between the check and the insert.

**Comment by omani** [comment]
so how does python eve do it?

**Comment by omani** [comment]
and what is the best option for me to be able to do this? misuse the id field?

**Comment by rs** [comment]
Eve does not guaranty unicity. It is just a pre-check before insertion, but if you want real unicity you have to put a unique index on your DB. This is something I didn't like in Eve, the false impression of safety is misleading.

The right way to do it is thru the constraint supported by your data layer (i.e.: unique indices). The storer should interpret the duplicate error correctly and report the right status code.

Does it make sense?

**Comment by omani** [comment]
yes. something like:
```
index := mgo.Index{
		Key:        []string{"field1", "field2", "etc."},
		Unique:     true,
		DropDups:   false,
		Background: true,
		Sparse:     true,
	}

	err := Session.DB(dbName).C(colname).EnsureIndex(index)
	if err != nil {
		panic("EnsureIndex failed. Aborting.")
	}
```

**Comment by omani** [comment]
thanks.
