### ISSUE TITLE
Resource Unbind process

### ISSUE THREAD

**Issue by xydac** [rs/rest-layer#94]
Just a thought process.
Can we add an index.UnBind() method along with Bind() so in case if needed, a given resource can also be unbounded dynamically.

This shouldn't be much of code and i can do that if thats fine ?

**Comment by rs** [comment]
Sure. Although, note that `Un/Bind()` is not thread safe, so you should not use those methods once the API is started.

**Comment by smyrman** [comment]
@xydac, @rs: I think it would be good to try to list a plausible real use-case before adding this. One that can't easily be solved already. You say it's not much code, but at least personally I don't think that's a good enough reason in itself.

Remember that every new method or function to the public API, however small, is another function that needs to documented and maintained in the future.

**Comment by smyrman** [comment]
It's just my personal opinion btw - you can feel free to ignore me ^.^

**Comment by rs** [comment]
That is a valid point. @xydac could you give us some more insight on how you plan to use this method?

**Comment by xydac** [comment]
@rs @smyrman  I guess you are right, having something thats not thread safe would create more of confusion. I had an assumption that it could be done in a thread safe manner.

**Comment by smyrman** [comment]
@rs, let's close this.

**Comment by smyrman** [comment]
I will close this for now.
