### ISSUE TITLE
Add support for async job

### ISSUE THREAD

**Issue by liubog2008** [rs/rest-layer#96]
Or hooks to customize response and StatusCode, for example, return 202.

link [http://farazdagi.com/blog/2014/rest-long-running-jobs/](http://farazdagi.com/blog/2014/rest-long-running-jobs/)

**Comment by smyrman** [comment]
@liubog2008, do you have a concrete example of what you want to do? 

Async job in itself would work just fine via a hook (or other mechanism). But even for long running jobs, 202 isn't _necessarily_ the right response, so it would be nice to better understand your use-case.

E.g. if i want to POST a job to `/jobs`, and the job is created immediately, 201 created would be the right response, even if the job takes a really long time to _complete_. More specifically, whether the job is complete or not is only the _state_ of the job, which could be represented as a field.

A more real use-case arise if you want to, say cancel `/jobs/42`, which for some reason may take a long time to complete. I don't know what would be the best API to allow for that, but it could be:
1. A custom HTTPHandler for requests ala `http POST localhost:1337/jobs/42/cancel kill=true`, returning 202 Accepted.
2. A rest-framework hook for `http PATCH localhost:1337/jobs/42 state=canceled` that somehow returned 202 Accepted.

Personally I think I would have preferred 1.

**Comment by liubog2008** [comment]
I hope to use `POST /clusters` to create a new cluster which is deployed with long time. So, I design another resource named `job` to track cluster creation. 

@smyrman `Job` can't be created (at least in my case) by user, it's a server behavior. The reason I don't use `job` as a field of `cluster` is that many log messages may be stored in `job`. A created cluster don't care about these messages.
```
# return 202 and Location is set to /jobs/{jid}
POST /clusters

# return 200 and job status is tracked (job phase, creating messages, progress)
GET /jobs/{jid} 

#  return 204 and stop creating the cluster
DELETE /jobs/{jid}

# By the way, delete cluster will also return 202 and another job will be created to delete cluster
DELETE /clusters/{cid}
```

Sorry for my pool English.

another link for the case: [http://restcookbook.com/Resources/asynchroneous-operations/](http://restcookbook.com/Resources/asynchroneous-operations/)

**Comment by smyrman** [comment]
> @smyrman Job can't be created (at least in my case) by user, it's a server behavior.

@liubog2008, that's alright, just wanted to understand your use-case. It looks like what you are trying to achieve is very sane ot me.

@rs, was there an easy way to support this?

**Comment by rs** [comment]
An idea could be to have a construct like that:

```go
cluster := schema.Schema{
    Fields: schema.Fields{
        "id": schema.IDField,
        "name": {
            Required: true,
            Validator: &schema.String{},
        },
    },
}

job := schema.Schema{
    Fields: schema.Fields{
        "id": schema.IDField,
        "payload": {
            Required: true,
            Schema: cluster,
        },
    },
}

index := resource.NewIndex()
jobs := index.Bind("jobs", job, mem.NewHandler, resource.DefaultConf)
clusters := index.Bind("clusters", cluster, mem.NewHandler, resource.DefaultConf)
clusters.SetAsyncResource(jobs, "payload") // please bear with me for terrible naming
```

So basically, when one resource is linked to another like that, we can expect the storage handler to create a resource in "jobs" with the "payload" field set to the payload of the POSTed document set on "clusters". As a result you get a `202` with a `Location` pointing to the newly created "jobs" (and no "cluster" resource created).

The "jobs" storage handler could be wrapped with a storage handler that would send any inserted document into a queue like Kafka so you can have some async processing managing those jobs. Or you can opt for a polling system when a cron lookup for "jobs" using some other fields to manage the state.

The `SetAsyncResource` logic could event be implemented as a hook so so we don't have clutter the `resource` API.

Would something like that fulfill you need @liubog2008?

**Comment by liubog2008** [comment]
Sorry for delay...
It looks good to me ~ @rs

**Comment by smyrman** [comment]
@rs, let's close this.
